// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: doge.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogeTopUpRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=address,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DogeTopUpRequest) Reset() {
	*x = DogeTopUpRequest{}
	mi := &file_doge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeTopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeTopUpRequest) ProtoMessage() {}

func (x *DogeTopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DogeTopUpRequest) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *DogeTopUpRequest) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

type DogeTopUpRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address string
}

func (b0 DogeTopUpRequest_builder) Build() *DogeTopUpRequest {
	m0 := &DogeTopUpRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	return m0
}

type DogeTopUpResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DogeTopUpResponse) Reset() {
	*x = DogeTopUpResponse{}
	mi := &file_doge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeTopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeTopUpResponse) ProtoMessage() {}

func (x *DogeTopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DogeTopUpResponse) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *DogeTopUpResponse) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type DogeTopUpResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 DogeTopUpResponse_builder) Build() *DogeTopUpResponse {
	m0 := &DogeTopUpResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type DogeConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeConfirmRequest) Reset() {
	*x = DogeConfirmRequest{}
	mi := &file_doge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeConfirmRequest) ProtoMessage() {}

func (x *DogeConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DogeConfirmRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DogeConfirmRequest_builder) Build() *DogeConfirmRequest {
	m0 := &DogeConfirmRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DogeConfirmResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DogeConfirmResponse) Reset() {
	*x = DogeConfirmResponse{}
	mi := &file_doge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeConfirmResponse) ProtoMessage() {}

func (x *DogeConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DogeConfirmResponse) GetValues() map[string]string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *DogeConfirmResponse) SetValues(v map[string]string) {
	x.xxx_hidden_Values = v
}

type DogeConfirmResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values map[string]string
}

func (b0 DogeConfirmResponse_builder) Build() *DogeConfirmResponse {
	m0 := &DogeConfirmResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

type DogeSendRequest struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EncodedTransactionHex string                 `protobuf:"bytes,1,opt,name=encoded_transaction_hex,json=encodedTransactionHex,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DogeSendRequest) Reset() {
	*x = DogeSendRequest{}
	mi := &file_doge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeSendRequest) ProtoMessage() {}

func (x *DogeSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DogeSendRequest) GetEncodedTransactionHex() string {
	if x != nil {
		return x.xxx_hidden_EncodedTransactionHex
	}
	return ""
}

func (x *DogeSendRequest) SetEncodedTransactionHex(v string) {
	x.xxx_hidden_EncodedTransactionHex = v
}

type DogeSendRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EncodedTransactionHex string
}

func (b0 DogeSendRequest_builder) Build() *DogeSendRequest {
	m0 := &DogeSendRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EncodedTransactionHex = b.EncodedTransactionHex
	return m0
}

type DogeSendResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DogeSendResponse) Reset() {
	*x = DogeSendResponse{}
	mi := &file_doge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeSendResponse) ProtoMessage() {}

func (x *DogeSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DogeSendResponse) GetTransactionId() string {
	if x != nil {
		return x.xxx_hidden_TransactionId
	}
	return ""
}

func (x *DogeSendResponse) SetTransactionId(v string) {
	x.xxx_hidden_TransactionId = v
}

type DogeSendResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TransactionId string
}

func (b0 DogeSendResponse_builder) Build() *DogeSendResponse {
	m0 := &DogeSendResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TransactionId = b.TransactionId
	return m0
}

var File_doge_proto protoreflect.FileDescriptor

const file_doge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"doge.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\"]\n" +
	"\x10DogeTopUpRequest\x12I\n" +
	"\aaddress\x18\x01 \x01(\tB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\aaddress\")\n" +
	"\x11DogeTopUpResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x14\n" +
	"\x12DogeConfirmRequest\"\x9f\x01\n" +
	"\x13DogeConfirmResponse\x12M\n" +
	"\x06values\x18\x01 \x03(\v25.fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0fDogeSendRequest\x126\n" +
	"\x17encoded_transaction_hex\x18\x01 \x01(\tR\x15encodedTransactionHex\"9\n" +
	"\x10DogeSendResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionIdB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\x06proto3"

var file_doge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_doge_proto_goTypes = []any{
	(*DogeTopUpRequest)(nil),    // 0: fractalengine.rpc.v1.DogeTopUpRequest
	(*DogeTopUpResponse)(nil),   // 1: fractalengine.rpc.v1.DogeTopUpResponse
	(*DogeConfirmRequest)(nil),  // 2: fractalengine.rpc.v1.DogeConfirmRequest
	(*DogeConfirmResponse)(nil), // 3: fractalengine.rpc.v1.DogeConfirmResponse
	(*DogeSendRequest)(nil),     // 4: fractalengine.rpc.v1.DogeSendRequest
	(*DogeSendResponse)(nil),    // 5: fractalengine.rpc.v1.DogeSendResponse
	nil,                         // 6: fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntry
}
var file_doge_proto_depIdxs = []int32{
	6, // 0: fractalengine.rpc.v1.DogeConfirmResponse.values:type_name -> fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_doge_proto_init() }
func file_doge_proto_init() {
	if File_doge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doge_proto_rawDesc), len(file_doge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_doge_proto_goTypes,
		DependencyIndexes: file_doge_proto_depIdxs,
		MessageInfos:      file_doge_proto_msgTypes,
	}.Build()
	File_doge_proto = out.File
	file_doge_proto_goTypes = nil
	file_doge_proto_depIdxs = nil
}
