// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: doge.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogeTopUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeTopUpRequest) Reset() {
	*x = DogeTopUpRequest{}
	mi := &file_doge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeTopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeTopUpRequest) ProtoMessage() {}

func (x *DogeTopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeTopUpRequest.ProtoReflect.Descriptor instead.
func (*DogeTopUpRequest) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{0}
}

func (x *DogeTopUpRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type DogeTopUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeTopUpResponse) Reset() {
	*x = DogeTopUpResponse{}
	mi := &file_doge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeTopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeTopUpResponse) ProtoMessage() {}

func (x *DogeTopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeTopUpResponse.ProtoReflect.Descriptor instead.
func (*DogeTopUpResponse) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{1}
}

func (x *DogeTopUpResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DogeConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeConfirmRequest) Reset() {
	*x = DogeConfirmRequest{}
	mi := &file_doge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeConfirmRequest) ProtoMessage() {}

func (x *DogeConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeConfirmRequest.ProtoReflect.Descriptor instead.
func (*DogeConfirmRequest) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{2}
}

type DogeConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeConfirmResponse) Reset() {
	*x = DogeConfirmResponse{}
	mi := &file_doge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeConfirmResponse) ProtoMessage() {}

func (x *DogeConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeConfirmResponse.ProtoReflect.Descriptor instead.
func (*DogeConfirmResponse) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{3}
}

func (x *DogeConfirmResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type DogeSendRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EncodedTransactionHex string                 `protobuf:"bytes,1,opt,name=encoded_transaction_hex,json=encodedTransactionHex,proto3" json:"encoded_transaction_hex,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DogeSendRequest) Reset() {
	*x = DogeSendRequest{}
	mi := &file_doge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeSendRequest) ProtoMessage() {}

func (x *DogeSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeSendRequest.ProtoReflect.Descriptor instead.
func (*DogeSendRequest) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{4}
}

func (x *DogeSendRequest) GetEncodedTransactionHex() string {
	if x != nil {
		return x.EncodedTransactionHex
	}
	return ""
}

type DogeSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DogeSendResponse) Reset() {
	*x = DogeSendResponse{}
	mi := &file_doge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DogeSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogeSendResponse) ProtoMessage() {}

func (x *DogeSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogeSendResponse.ProtoReflect.Descriptor instead.
func (*DogeSendResponse) Descriptor() ([]byte, []int) {
	return file_doge_proto_rawDescGZIP(), []int{5}
}

func (x *DogeSendResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

var File_doge_proto protoreflect.FileDescriptor

const file_doge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"doge.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\vtypes.proto\"K\n" +
	"\x10DogeTopUpRequest\x127\n" +
	"\aaddress\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\aaddress\")\n" +
	"\x11DogeTopUpResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x14\n" +
	"\x12DogeConfirmRequest\"\x9f\x01\n" +
	"\x13DogeConfirmResponse\x12M\n" +
	"\x06values\x18\x01 \x03(\v25.fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x0fDogeSendRequest\x126\n" +
	"\x17encoded_transaction_hex\x18\x01 \x01(\tR\x15encodedTransactionHex\"9\n" +
	"\x10DogeSendResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionIdB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\x06proto3"

var (
	file_doge_proto_rawDescOnce sync.Once
	file_doge_proto_rawDescData []byte
)

func file_doge_proto_rawDescGZIP() []byte {
	file_doge_proto_rawDescOnce.Do(func() {
		file_doge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doge_proto_rawDesc), len(file_doge_proto_rawDesc)))
	})
	return file_doge_proto_rawDescData
}

var file_doge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_doge_proto_goTypes = []any{
	(*DogeTopUpRequest)(nil),    // 0: fractalengine.rpc.v1.DogeTopUpRequest
	(*DogeTopUpResponse)(nil),   // 1: fractalengine.rpc.v1.DogeTopUpResponse
	(*DogeConfirmRequest)(nil),  // 2: fractalengine.rpc.v1.DogeConfirmRequest
	(*DogeConfirmResponse)(nil), // 3: fractalengine.rpc.v1.DogeConfirmResponse
	(*DogeSendRequest)(nil),     // 4: fractalengine.rpc.v1.DogeSendRequest
	(*DogeSendResponse)(nil),    // 5: fractalengine.rpc.v1.DogeSendResponse
	nil,                         // 6: fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntry
	(*Address)(nil),             // 7: fractalengine.rpc.v1.Address
}
var file_doge_proto_depIdxs = []int32{
	7, // 0: fractalengine.rpc.v1.DogeTopUpRequest.address:type_name -> fractalengine.rpc.v1.Address
	6, // 1: fractalengine.rpc.v1.DogeConfirmResponse.values:type_name -> fractalengine.rpc.v1.DogeConfirmResponse.ValuesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_doge_proto_init() }
func file_doge_proto_init() {
	if File_doge_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doge_proto_rawDesc), len(file_doge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_doge_proto_goTypes,
		DependencyIndexes: file_doge_proto_depIdxs,
		MessageInfos:      file_doge_proto_msgTypes,
	}.Build()
	File_doge_proto = out.File
	file_doge_proto_goTypes = nil
	file_doge_proto_depIdxs = nil
}
