// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthResponse struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Chain              *string                `protobuf:"bytes,1,opt,name=chain"`
	xxx_hidden_CurrentBlockHeight int32                  `protobuf:"varint,2,opt,name=current_block_height,json=currentBlockHeight"`
	xxx_hidden_LatestBlockHeight  int32                  `protobuf:"varint,3,opt,name=latest_block_height,json=latestBlockHeight"`
	xxx_hidden_UpdatedAt          *string                `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_Version            *string                `protobuf:"bytes,5,opt,name=version"`
	xxx_hidden_WalletsEnabled     bool                   `protobuf:"varint,6,opt,name=wallets_enabled,json=walletsEnabled"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetHealthResponse) GetChain() string {
	if x != nil {
		if x.xxx_hidden_Chain != nil {
			return *x.xxx_hidden_Chain
		}
		return ""
	}
	return ""
}

func (x *GetHealthResponse) GetCurrentBlockHeight() int32 {
	if x != nil {
		return x.xxx_hidden_CurrentBlockHeight
	}
	return 0
}

func (x *GetHealthResponse) GetLatestBlockHeight() int32 {
	if x != nil {
		return x.xxx_hidden_LatestBlockHeight
	}
	return 0
}

func (x *GetHealthResponse) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *GetHealthResponse) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GetHealthResponse) GetWalletsEnabled() bool {
	if x != nil {
		return x.xxx_hidden_WalletsEnabled
	}
	return false
}

func (x *GetHealthResponse) SetChain(v string) {
	x.xxx_hidden_Chain = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *GetHealthResponse) SetCurrentBlockHeight(v int32) {
	x.xxx_hidden_CurrentBlockHeight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *GetHealthResponse) SetLatestBlockHeight(v int32) {
	x.xxx_hidden_LatestBlockHeight = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *GetHealthResponse) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *GetHealthResponse) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *GetHealthResponse) SetWalletsEnabled(v bool) {
	x.xxx_hidden_WalletsEnabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *GetHealthResponse) HasChain() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetHealthResponse) HasCurrentBlockHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetHealthResponse) HasLatestBlockHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetHealthResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetHealthResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GetHealthResponse) HasWalletsEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GetHealthResponse) ClearChain() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Chain = nil
}

func (x *GetHealthResponse) ClearCurrentBlockHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CurrentBlockHeight = 0
}

func (x *GetHealthResponse) ClearLatestBlockHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LatestBlockHeight = 0
}

func (x *GetHealthResponse) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UpdatedAt = nil
}

func (x *GetHealthResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = nil
}

func (x *GetHealthResponse) ClearWalletsEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_WalletsEnabled = false
}

type GetHealthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Chain              *string
	CurrentBlockHeight *int32
	LatestBlockHeight  *int32
	UpdatedAt          *string
	Version            *string
	WalletsEnabled     *bool
}

func (b0 GetHealthResponse_builder) Build() *GetHealthResponse {
	m0 := &GetHealthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Chain != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Chain = b.Chain
	}
	if b.CurrentBlockHeight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_CurrentBlockHeight = *b.CurrentBlockHeight
	}
	if b.LatestBlockHeight != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_LatestBlockHeight = *b.LatestBlockHeight
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Version = b.Version
	}
	if b.WalletsEnabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_WalletsEnabled = *b.WalletsEnabled
	}
	return m0
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetHealthRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetHealthRequest_builder) Build() *GetHealthRequest {
	m0 := &GetHealthRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x14fractalengine.rpc.v1\"\xed\x01\n" +
	"\x11GetHealthResponse\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x120\n" +
	"\x14current_block_height\x18\x02 \x01(\x05R\x12currentBlockHeight\x12.\n" +
	"\x13latest_block_height\x18\x03 \x01(\x05R\x11latestBlockHeight\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12'\n" +
	"\x0fwallets_enabled\x18\x06 \x01(\bR\x0ewalletsEnabled\"\x12\n" +
	"\x10GetHealthRequestB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\beditionsp\xe8\a"

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_health_proto_goTypes = []any{
	(*GetHealthResponse)(nil), // 0: fractalengine.rpc.v1.GetHealthResponse
	(*GetHealthRequest)(nil),  // 1: fractalengine.rpc.v1.GetHealthRequest
}
var file_health_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
