// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoices.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInvoicesRequest struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Address  string                  `protobuf:"bytes,1,opt,name=address,proto3"`
	xxx_hidden_Limit    *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=limit,proto3"`
	xxx_hidden_Page     *wrapperspb.Int32Value  `protobuf:"bytes,3,opt,name=page,proto3"`
	xxx_hidden_MintHash *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInvoicesRequest) Reset() {
	*x = GetInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesRequest) ProtoMessage() {}

func (x *GetInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInvoicesRequest) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *GetInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetInvoicesRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetInvoicesRequest) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *GetInvoicesRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetInvoicesRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetInvoicesRequest) SetMintHash(v *wrapperspb.StringValue) {
	x.xxx_hidden_MintHash = v
}

func (x *GetInvoicesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetInvoicesRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetInvoicesRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetInvoicesRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetInvoicesRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetInvoicesRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

type GetInvoicesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address  string
	Limit    *wrapperspb.Int32Value
	Page     *wrapperspb.Int32Value
	MintHash *wrapperspb.StringValue
}

func (b0 GetInvoicesRequest_builder) Build() *GetInvoicesRequest {
	m0 := &GetInvoicesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	return m0
}

type GetAllInvoicesRequest struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Limit    *wrapperspb.Int32Value  `protobuf:"bytes,1,opt,name=limit,proto3"`
	xxx_hidden_Page     *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=page,proto3"`
	xxx_hidden_MintHash *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAllInvoicesRequest) Reset() {
	*x = GetAllInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesRequest) ProtoMessage() {}

func (x *GetAllInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetAllInvoicesRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetAllInvoicesRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetAllInvoicesRequest) SetMintHash(v *wrapperspb.StringValue) {
	x.xxx_hidden_MintHash = v
}

func (x *GetAllInvoicesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetAllInvoicesRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetAllInvoicesRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetAllInvoicesRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetAllInvoicesRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetAllInvoicesRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

type GetAllInvoicesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit    *wrapperspb.Int32Value
	Page     *wrapperspb.Int32Value
	MintHash *wrapperspb.StringValue
}

func (b0 GetAllInvoicesRequest_builder) Build() *GetAllInvoicesRequest {
	m0 := &GetAllInvoicesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	return m0
}

type GetInvoicesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invoices *[]*Invoice            `protobuf:"bytes,1,rep,name=invoices,proto3"`
	xxx_hidden_Limit    int32                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Page     int32                  `protobuf:"varint,3,opt,name=page,proto3"`
	xxx_hidden_Total    int32                  `protobuf:"varint,4,opt,name=total,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInvoicesResponse) Reset() {
	*x = GetInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesResponse) ProtoMessage() {}

func (x *GetInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		if x.xxx_hidden_Invoices != nil {
			return *x.xxx_hidden_Invoices
		}
	}
	return nil
}

func (x *GetInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetInvoicesResponse) SetInvoices(v []*Invoice) {
	x.xxx_hidden_Invoices = &v
}

func (x *GetInvoicesResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *GetInvoicesResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
}

func (x *GetInvoicesResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
}

type GetInvoicesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invoices []*Invoice
	Limit    int32
	Page     int32
	Total    int32
}

func (b0 GetInvoicesResponse_builder) Build() *GetInvoicesResponse {
	m0 := &GetInvoicesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invoices = &b.Invoices
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_Total = b.Total
	return m0
}

type GetAllInvoicesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invoices *[]*Invoice            `protobuf:"bytes,1,rep,name=invoices,proto3"`
	xxx_hidden_Limit    int32                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Page     int32                  `protobuf:"varint,3,opt,name=page,proto3"`
	xxx_hidden_Total    int32                  `protobuf:"varint,4,opt,name=total,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		if x.xxx_hidden_Invoices != nil {
			return *x.xxx_hidden_Invoices
		}
	}
	return nil
}

func (x *GetAllInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetAllInvoicesResponse) SetInvoices(v []*Invoice) {
	x.xxx_hidden_Invoices = &v
}

func (x *GetAllInvoicesResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *GetAllInvoicesResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
}

func (x *GetAllInvoicesResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
}

type GetAllInvoicesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invoices []*Invoice
	Limit    int32
	Page     int32
	Total    int32
}

func (b0 GetAllInvoicesResponse_builder) Build() *GetAllInvoicesResponse {
	m0 := &GetAllInvoicesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invoices = &b.Invoices
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_Total = b.Total
	return m0
}

type CreateInvoiceSignatureRequest struct {
	state              protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_Payload *CreateInvoiceSignatureRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequest) Reset() {
	*x = CreateInvoiceSignatureRequest{}
	mi := &file_invoices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequest) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureRequest) GetPayload() *CreateInvoiceSignatureRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateInvoiceSignatureRequest) SetPayload(v *CreateInvoiceSignatureRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateInvoiceSignatureRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateInvoiceSignatureRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type CreateInvoiceSignatureRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload *CreateInvoiceSignatureRequestPayload
}

func (b0 CreateInvoiceSignatureRequest_builder) Build() *CreateInvoiceSignatureRequest {
	m0 := &CreateInvoiceSignatureRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type CreateInvoiceSignatureRequestPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InvoiceHash string                 `protobuf:"bytes,1,opt,name=invoice_hash,json=invoiceHash,proto3"`
	xxx_hidden_PublicKey   string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3"`
	xxx_hidden_Signature   string                 `protobuf:"bytes,3,opt,name=signature,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequestPayload) Reset() {
	*x = CreateInvoiceSignatureRequestPayload{}
	mi := &file_invoices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureRequestPayload) GetInvoiceHash() string {
	if x != nil {
		return x.xxx_hidden_InvoiceHash
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetPublicKey() string {
	if x != nil {
		return x.xxx_hidden_PublicKey
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetSignature() string {
	if x != nil {
		return x.xxx_hidden_Signature
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) SetInvoiceHash(v string) {
	x.xxx_hidden_InvoiceHash = v
}

func (x *CreateInvoiceSignatureRequestPayload) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = v
}

func (x *CreateInvoiceSignatureRequestPayload) SetSignature(v string) {
	x.xxx_hidden_Signature = v
}

type CreateInvoiceSignatureRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InvoiceHash string
	PublicKey   string
	Signature   string
}

func (b0 CreateInvoiceSignatureRequestPayload_builder) Build() *CreateInvoiceSignatureRequestPayload {
	m0 := &CreateInvoiceSignatureRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InvoiceHash = b.InvoiceHash
	x.xxx_hidden_PublicKey = b.PublicKey
	x.xxx_hidden_Signature = b.Signature
	return m0
}

type CreateInvoiceSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureResponse) Reset() {
	*x = CreateInvoiceSignatureResponse{}
	mi := &file_invoices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureResponse) ProtoMessage() {}

func (x *CreateInvoiceSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *CreateInvoiceSignatureResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

type CreateInvoiceSignatureResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 CreateInvoiceSignatureResponse_builder) Build() *CreateInvoiceSignatureResponse {
	m0 := &CreateInvoiceSignatureResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type CreateInvoiceRequest struct {
	state                protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Payload   *CreateInvoiceRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3"`
	xxx_hidden_PublicKey string                       `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3"`
	xxx_hidden_Signature string                       `protobuf:"bytes,3,opt,name=signature,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_invoices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceRequest) GetPayload() *CreateInvoiceRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateInvoiceRequest) GetPublicKey() string {
	if x != nil {
		return x.xxx_hidden_PublicKey
	}
	return ""
}

func (x *CreateInvoiceRequest) GetSignature() string {
	if x != nil {
		return x.xxx_hidden_Signature
	}
	return ""
}

func (x *CreateInvoiceRequest) SetPayload(v *CreateInvoiceRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateInvoiceRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = v
}

func (x *CreateInvoiceRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = v
}

func (x *CreateInvoiceRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateInvoiceRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type CreateInvoiceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *CreateInvoiceRequestPayload
	PublicKey string
	Signature string
}

func (b0 CreateInvoiceRequest_builder) Build() *CreateInvoiceRequest {
	m0 := &CreateInvoiceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	x.xxx_hidden_PublicKey = b.PublicKey
	x.xxx_hidden_Signature = b.Signature
	return m0
}

type CreateInvoiceRequestPayload struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PaymentAddress string                 `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress,proto3"`
	xxx_hidden_BuyerAddress   string                 `protobuf:"bytes,2,opt,name=buyer_address,json=buyerAddress,proto3"`
	xxx_hidden_MintHash       string                 `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3"`
	xxx_hidden_Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3"`
	xxx_hidden_Price          int32                  `protobuf:"varint,5,opt,name=price,proto3"`
	xxx_hidden_SellerAddress  string                 `protobuf:"bytes,6,opt,name=seller_address,json=sellerAddress,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateInvoiceRequestPayload) Reset() {
	*x = CreateInvoiceRequestPayload{}
	mi := &file_invoices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceRequestPayload) GetPaymentAddress() string {
	if x != nil {
		return x.xxx_hidden_PaymentAddress
	}
	return ""
}

func (x *CreateInvoiceRequestPayload) GetBuyerAddress() string {
	if x != nil {
		return x.xxx_hidden_BuyerAddress
	}
	return ""
}

func (x *CreateInvoiceRequestPayload) GetMintHash() string {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return ""
}

func (x *CreateInvoiceRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.xxx_hidden_Price
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetSellerAddress() string {
	if x != nil {
		return x.xxx_hidden_SellerAddress
	}
	return ""
}

func (x *CreateInvoiceRequestPayload) SetPaymentAddress(v string) {
	x.xxx_hidden_PaymentAddress = v
}

func (x *CreateInvoiceRequestPayload) SetBuyerAddress(v string) {
	x.xxx_hidden_BuyerAddress = v
}

func (x *CreateInvoiceRequestPayload) SetMintHash(v string) {
	x.xxx_hidden_MintHash = v
}

func (x *CreateInvoiceRequestPayload) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
}

func (x *CreateInvoiceRequestPayload) SetPrice(v int32) {
	x.xxx_hidden_Price = v
}

func (x *CreateInvoiceRequestPayload) SetSellerAddress(v string) {
	x.xxx_hidden_SellerAddress = v
}

type CreateInvoiceRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PaymentAddress string
	BuyerAddress   string
	MintHash       string
	Quantity       int32
	Price          int32
	SellerAddress  string
}

func (b0 CreateInvoiceRequestPayload_builder) Build() *CreateInvoiceRequestPayload {
	m0 := &CreateInvoiceRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PaymentAddress = b.PaymentAddress
	x.xxx_hidden_BuyerAddress = b.BuyerAddress
	x.xxx_hidden_MintHash = b.MintHash
	x.xxx_hidden_Quantity = b.Quantity
	x.xxx_hidden_Price = b.Price
	x.xxx_hidden_SellerAddress = b.SellerAddress
	return m0
}

type CreateInvoiceResponse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash                   string                 `protobuf:"bytes,1,opt,name=hash,proto3"`
	xxx_hidden_EncodedTransactionBody string                 `protobuf:"bytes,2,opt,name=encoded_transaction_body,json=encodedTransactionBody,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_invoices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceResponse) GetHash() string {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return ""
}

func (x *CreateInvoiceResponse) GetEncodedTransactionBody() string {
	if x != nil {
		return x.xxx_hidden_EncodedTransactionBody
	}
	return ""
}

func (x *CreateInvoiceResponse) SetHash(v string) {
	x.xxx_hidden_Hash = v
}

func (x *CreateInvoiceResponse) SetEncodedTransactionBody(v string) {
	x.xxx_hidden_EncodedTransactionBody = v
}

type CreateInvoiceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hash                   string
	EncodedTransactionBody string
}

func (b0 CreateInvoiceResponse_builder) Build() *CreateInvoiceResponse {
	m0 := &CreateInvoiceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hash = b.Hash
	x.xxx_hidden_EncodedTransactionBody = b.EncodedTransactionBody
	return m0
}

var File_invoices_proto protoreflect.FileDescriptor

const file_invoices_proto_rawDesc = "" +
	"\n" +
	"\x0einvoices.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\"\x98\x02\n" +
	"\x12GetInvoicesRequest\x12I\n" +
	"\aaddress\x18\x01 \x01(\tB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\aaddress\x121\n" +
	"\x05limit\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x12S\n" +
	"\tmint_hash\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\"\xd0\x01\n" +
	"\x15GetAllInvoicesRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x12S\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\"\x90\x01\n" +
	"\x13GetInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\x93\x01\n" +
	"\x16GetAllInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"u\n" +
	"\x1dCreateInvoiceSignatureRequest\x12T\n" +
	"\apayload\x18\x01 \x01(\v2:.fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayloadR\apayload\"\xb4\x01\n" +
	"$CreateInvoiceSignatureRequestPayload\x12=\n" +
	"\finvoice_hash\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\vinvoiceHash\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"0\n" +
	"\x1eCreateInvoiceSignatureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x14CreateInvoiceRequest\x12K\n" +
	"\apayload\x18\x01 \x01(\v21.fractalengine.rpc.v1.CreateInvoiceRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\xa8\x03\n" +
	"\x1bCreateInvoiceRequestPayload\x12Z\n" +
	"\x0fpayment_address\x18\x01 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\x0epaymentAddress\x12V\n" +
	"\rbuyer_address\x18\x02 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\fbuyerAddress\x127\n" +
	"\tmint_hash\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\bmintHash\x12#\n" +
	"\bquantity\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\x12X\n" +
	"\x0eseller_address\x18\x06 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\rsellerAddress\"\x7f\n" +
	"\x15CreateInvoiceResponse\x12,\n" +
	"\x04hash\x18\x01 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\x04hash\x128\n" +
	"\x18encoded_transaction_body\x18\x02 \x01(\tR\x16encodedTransactionBodyB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\x06proto3"

var file_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_invoices_proto_goTypes = []any{
	(*GetInvoicesRequest)(nil),                   // 0: fractalengine.rpc.v1.GetInvoicesRequest
	(*GetAllInvoicesRequest)(nil),                // 1: fractalengine.rpc.v1.GetAllInvoicesRequest
	(*GetInvoicesResponse)(nil),                  // 2: fractalengine.rpc.v1.GetInvoicesResponse
	(*GetAllInvoicesResponse)(nil),               // 3: fractalengine.rpc.v1.GetAllInvoicesResponse
	(*CreateInvoiceSignatureRequest)(nil),        // 4: fractalengine.rpc.v1.CreateInvoiceSignatureRequest
	(*CreateInvoiceSignatureRequestPayload)(nil), // 5: fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	(*CreateInvoiceSignatureResponse)(nil),       // 6: fractalengine.rpc.v1.CreateInvoiceSignatureResponse
	(*CreateInvoiceRequest)(nil),                 // 7: fractalengine.rpc.v1.CreateInvoiceRequest
	(*CreateInvoiceRequestPayload)(nil),          // 8: fractalengine.rpc.v1.CreateInvoiceRequestPayload
	(*CreateInvoiceResponse)(nil),                // 9: fractalengine.rpc.v1.CreateInvoiceResponse
	(*wrapperspb.Int32Value)(nil),                // 10: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),               // 11: google.protobuf.StringValue
	(*Invoice)(nil),                              // 12: fractalengine.rpc.v1.Invoice
}
var file_invoices_proto_depIdxs = []int32{
	10, // 0: fractalengine.rpc.v1.GetInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	10, // 1: fractalengine.rpc.v1.GetInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	11, // 2: fractalengine.rpc.v1.GetInvoicesRequest.mint_hash:type_name -> google.protobuf.StringValue
	10, // 3: fractalengine.rpc.v1.GetAllInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	10, // 4: fractalengine.rpc.v1.GetAllInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	11, // 5: fractalengine.rpc.v1.GetAllInvoicesRequest.mint_hash:type_name -> google.protobuf.StringValue
	12, // 6: fractalengine.rpc.v1.GetInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	12, // 7: fractalengine.rpc.v1.GetAllInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	5,  // 8: fractalengine.rpc.v1.CreateInvoiceSignatureRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	8,  // 9: fractalengine.rpc.v1.CreateInvoiceRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceRequestPayload
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_invoices_proto_init() }
func file_invoices_proto_init() {
	if File_invoices_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoices_proto_goTypes,
		DependencyIndexes: file_invoices_proto_depIdxs,
		MessageInfos:      file_invoices_proto_msgTypes,
	}.Build()
	File_invoices_proto = out.File
	file_invoices_proto_goTypes = nil
	file_invoices_proto_depIdxs = nil
}
