// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoices.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInvoicesRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address  *Address               `protobuf:"bytes,1,opt,name=address"`
	xxx_hidden_Limit    *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=limit"`
	xxx_hidden_Page     *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=page"`
	xxx_hidden_MintHash *Hash                  `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInvoicesRequest) Reset() {
	*x = GetInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesRequest) ProtoMessage() {}

func (x *GetInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInvoicesRequest) GetAddress() *Address {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return nil
}

func (x *GetInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetInvoicesRequest) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetInvoicesRequest) SetAddress(v *Address) {
	x.xxx_hidden_Address = v
}

func (x *GetInvoicesRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetInvoicesRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetInvoicesRequest) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *GetInvoicesRequest) HasAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Address != nil
}

func (x *GetInvoicesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetInvoicesRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetInvoicesRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetInvoicesRequest) ClearAddress() {
	x.xxx_hidden_Address = nil
}

func (x *GetInvoicesRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetInvoicesRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetInvoicesRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

type GetInvoicesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address  *Address
	Limit    *wrapperspb.Int32Value
	Page     *wrapperspb.Int32Value
	MintHash *Hash
}

func (b0 GetInvoicesRequest_builder) Build() *GetInvoicesRequest {
	m0 := &GetInvoicesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	return m0
}

type GetAllInvoicesRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit    *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit"`
	xxx_hidden_Page     *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_MintHash *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAllInvoicesRequest) Reset() {
	*x = GetAllInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesRequest) ProtoMessage() {}

func (x *GetAllInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetAllInvoicesRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetAllInvoicesRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetAllInvoicesRequest) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *GetAllInvoicesRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetAllInvoicesRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetAllInvoicesRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetAllInvoicesRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetAllInvoicesRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetAllInvoicesRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

type GetAllInvoicesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit    *wrapperspb.Int32Value
	Page     *wrapperspb.Int32Value
	MintHash *Hash
}

func (b0 GetAllInvoicesRequest_builder) Build() *GetAllInvoicesRequest {
	m0 := &GetAllInvoicesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	return m0
}

type GetInvoicesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invoices    *[]*Invoice            `protobuf:"bytes,1,rep,name=invoices"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Page        int32                  `protobuf:"varint,3,opt,name=page"`
	xxx_hidden_Total       int32                  `protobuf:"varint,4,opt,name=total"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetInvoicesResponse) Reset() {
	*x = GetInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesResponse) ProtoMessage() {}

func (x *GetInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		if x.xxx_hidden_Invoices != nil {
			return *x.xxx_hidden_Invoices
		}
	}
	return nil
}

func (x *GetInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetInvoicesResponse) SetInvoices(v []*Invoice) {
	x.xxx_hidden_Invoices = &v
}

func (x *GetInvoicesResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GetInvoicesResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GetInvoicesResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *GetInvoicesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetInvoicesResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetInvoicesResponse) HasTotal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetInvoicesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *GetInvoicesResponse) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Page = 0
}

func (x *GetInvoicesResponse) ClearTotal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Total = 0
}

type GetInvoicesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invoices []*Invoice
	Limit    *int32
	Page     *int32
	Total    *int32
}

func (b0 GetInvoicesResponse_builder) Build() *GetInvoicesResponse {
	m0 := &GetInvoicesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invoices = &b.Invoices
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Page = *b.Page
	}
	if b.Total != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Total = *b.Total
	}
	return m0
}

type GetAllInvoicesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Invoices    *[]*Invoice            `protobuf:"bytes,1,rep,name=invoices"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Page        int32                  `protobuf:"varint,3,opt,name=page"`
	xxx_hidden_Total       int32                  `protobuf:"varint,4,opt,name=total"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAllInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		if x.xxx_hidden_Invoices != nil {
			return *x.xxx_hidden_Invoices
		}
	}
	return nil
}

func (x *GetAllInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetAllInvoicesResponse) SetInvoices(v []*Invoice) {
	x.xxx_hidden_Invoices = &v
}

func (x *GetAllInvoicesResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GetAllInvoicesResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GetAllInvoicesResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *GetAllInvoicesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetAllInvoicesResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetAllInvoicesResponse) HasTotal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetAllInvoicesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

func (x *GetAllInvoicesResponse) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Page = 0
}

func (x *GetAllInvoicesResponse) ClearTotal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Total = 0
}

type GetAllInvoicesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Invoices []*Invoice
	Limit    *int32
	Page     *int32
	Total    *int32
}

func (b0 GetAllInvoicesResponse_builder) Build() *GetAllInvoicesResponse {
	m0 := &GetAllInvoicesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Invoices = &b.Invoices
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Page = *b.Page
	}
	if b.Total != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Total = *b.Total
	}
	return m0
}

type CreateInvoiceSignatureRequest struct {
	state              protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_Payload *CreateInvoiceSignatureRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequest) Reset() {
	*x = CreateInvoiceSignatureRequest{}
	mi := &file_invoices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequest) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureRequest) GetPayload() *CreateInvoiceSignatureRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateInvoiceSignatureRequest) SetPayload(v *CreateInvoiceSignatureRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateInvoiceSignatureRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateInvoiceSignatureRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

type CreateInvoiceSignatureRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload *CreateInvoiceSignatureRequestPayload
}

func (b0 CreateInvoiceSignatureRequest_builder) Build() *CreateInvoiceSignatureRequest {
	m0 := &CreateInvoiceSignatureRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type CreateInvoiceSignatureRequestPayload struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InvoiceHash *string                `protobuf:"bytes,1,opt,name=invoice_hash,json=invoiceHash"`
	xxx_hidden_PublicKey   *string                `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequestPayload) Reset() {
	*x = CreateInvoiceSignatureRequestPayload{}
	mi := &file_invoices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureRequestPayload) GetInvoiceHash() string {
	if x != nil {
		if x.xxx_hidden_InvoiceHash != nil {
			return *x.xxx_hidden_InvoiceHash
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) SetInvoiceHash(v string) {
	x.xxx_hidden_InvoiceHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CreateInvoiceSignatureRequestPayload) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateInvoiceSignatureRequestPayload) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateInvoiceSignatureRequestPayload) HasInvoiceHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateInvoiceSignatureRequestPayload) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateInvoiceSignatureRequestPayload) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateInvoiceSignatureRequestPayload) ClearInvoiceHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InvoiceHash = nil
}

func (x *CreateInvoiceSignatureRequestPayload) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *CreateInvoiceSignatureRequestPayload) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type CreateInvoiceSignatureRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InvoiceHash *string
	PublicKey   *string
	Signature   *string
}

func (b0 CreateInvoiceSignatureRequestPayload_builder) Build() *CreateInvoiceSignatureRequestPayload {
	m0 := &CreateInvoiceSignatureRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InvoiceHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_InvoiceHash = b.InvoiceHash
	}
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type CreateInvoiceSignatureResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureResponse) Reset() {
	*x = CreateInvoiceSignatureResponse{}
	mi := &file_invoices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureResponse) ProtoMessage() {}

func (x *CreateInvoiceSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceSignatureResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceSignatureResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateInvoiceSignatureResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateInvoiceSignatureResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type CreateInvoiceSignatureResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 CreateInvoiceSignatureResponse_builder) Build() *CreateInvoiceSignatureResponse {
	m0 := &CreateInvoiceSignatureResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type CreateInvoiceRequest struct {
	state                  protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Payload     *CreateInvoiceRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	xxx_hidden_PublicKey   *string                      `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                      `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_invoices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceRequest) GetPayload() *CreateInvoiceRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateInvoiceRequest) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceRequest) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceRequest) SetPayload(v *CreateInvoiceRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateInvoiceRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateInvoiceRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateInvoiceRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateInvoiceRequest) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateInvoiceRequest) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateInvoiceRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *CreateInvoiceRequest) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *CreateInvoiceRequest) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type CreateInvoiceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *CreateInvoiceRequestPayload
	PublicKey *string
	Signature *string
}

func (b0 CreateInvoiceRequest_builder) Build() *CreateInvoiceRequest {
	m0 := &CreateInvoiceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type CreateInvoiceRequestPayload struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PaymentAddress *Address               `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress"`
	xxx_hidden_BuyerAddress   *Address               `protobuf:"bytes,2,opt,name=buyer_address,json=buyerAddress"`
	xxx_hidden_MintHash       *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash"`
	xxx_hidden_Quantity       int32                  `protobuf:"varint,4,opt,name=quantity"`
	xxx_hidden_Price          int32                  `protobuf:"varint,5,opt,name=price"`
	xxx_hidden_SellerAddress  *Address               `protobuf:"bytes,6,opt,name=seller_address,json=sellerAddress"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateInvoiceRequestPayload) Reset() {
	*x = CreateInvoiceRequestPayload{}
	mi := &file_invoices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceRequestPayload) GetPaymentAddress() *Address {
	if x != nil {
		return x.xxx_hidden_PaymentAddress
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetBuyerAddress() *Address {
	if x != nil {
		return x.xxx_hidden_BuyerAddress
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.xxx_hidden_Price
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetSellerAddress() *Address {
	if x != nil {
		return x.xxx_hidden_SellerAddress
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) SetPaymentAddress(v *Address) {
	x.xxx_hidden_PaymentAddress = v
}

func (x *CreateInvoiceRequestPayload) SetBuyerAddress(v *Address) {
	x.xxx_hidden_BuyerAddress = v
}

func (x *CreateInvoiceRequestPayload) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *CreateInvoiceRequestPayload) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *CreateInvoiceRequestPayload) SetPrice(v int32) {
	x.xxx_hidden_Price = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CreateInvoiceRequestPayload) SetSellerAddress(v *Address) {
	x.xxx_hidden_SellerAddress = v
}

func (x *CreateInvoiceRequestPayload) HasPaymentAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PaymentAddress != nil
}

func (x *CreateInvoiceRequestPayload) HasBuyerAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BuyerAddress != nil
}

func (x *CreateInvoiceRequestPayload) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *CreateInvoiceRequestPayload) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateInvoiceRequestPayload) HasPrice() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateInvoiceRequestPayload) HasSellerAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SellerAddress != nil
}

func (x *CreateInvoiceRequestPayload) ClearPaymentAddress() {
	x.xxx_hidden_PaymentAddress = nil
}

func (x *CreateInvoiceRequestPayload) ClearBuyerAddress() {
	x.xxx_hidden_BuyerAddress = nil
}

func (x *CreateInvoiceRequestPayload) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

func (x *CreateInvoiceRequestPayload) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Quantity = 0
}

func (x *CreateInvoiceRequestPayload) ClearPrice() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Price = 0
}

func (x *CreateInvoiceRequestPayload) ClearSellerAddress() {
	x.xxx_hidden_SellerAddress = nil
}

type CreateInvoiceRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PaymentAddress *Address
	BuyerAddress   *Address
	MintHash       *Hash
	Quantity       *int32
	Price          *int32
	SellerAddress  *Address
}

func (b0 CreateInvoiceRequestPayload_builder) Build() *CreateInvoiceRequestPayload {
	m0 := &CreateInvoiceRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PaymentAddress = b.PaymentAddress
	x.xxx_hidden_BuyerAddress = b.BuyerAddress
	x.xxx_hidden_MintHash = b.MintHash
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	if b.Price != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Price = *b.Price
	}
	x.xxx_hidden_SellerAddress = b.SellerAddress
	return m0
}

type CreateInvoiceResponse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hash                   *Hash                  `protobuf:"bytes,1,opt,name=hash"`
	xxx_hidden_EncodedTransactionBody *string                `protobuf:"bytes,2,opt,name=encoded_transaction_body,json=encodedTransactionBody"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_invoices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateInvoiceResponse) GetHash() *Hash {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *CreateInvoiceResponse) GetEncodedTransactionBody() string {
	if x != nil {
		if x.xxx_hidden_EncodedTransactionBody != nil {
			return *x.xxx_hidden_EncodedTransactionBody
		}
		return ""
	}
	return ""
}

func (x *CreateInvoiceResponse) SetHash(v *Hash) {
	x.xxx_hidden_Hash = v
}

func (x *CreateInvoiceResponse) SetEncodedTransactionBody(v string) {
	x.xxx_hidden_EncodedTransactionBody = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateInvoiceResponse) HasHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hash != nil
}

func (x *CreateInvoiceResponse) HasEncodedTransactionBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateInvoiceResponse) ClearHash() {
	x.xxx_hidden_Hash = nil
}

func (x *CreateInvoiceResponse) ClearEncodedTransactionBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncodedTransactionBody = nil
}

type CreateInvoiceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hash                   *Hash
	EncodedTransactionBody *string
}

func (b0 CreateInvoiceResponse_builder) Build() *CreateInvoiceResponse {
	m0 := &CreateInvoiceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hash = b.Hash
	if b.EncodedTransactionBody != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EncodedTransactionBody = b.EncodedTransactionBody
	}
	return m0
}

var File_invoices_proto protoreflect.FileDescriptor

const file_invoices_proto_rawDesc = "" +
	"\n" +
	"\x0einvoices.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\x1a\vtypes.proto\"\xea\x01\n" +
	"\x12GetInvoicesRequest\x127\n" +
	"\aaddress\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\aaddress\x121\n" +
	"\x05limit\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x04 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\"\xb4\x01\n" +
	"\x15GetAllInvoicesRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\"\x90\x01\n" +
	"\x13GetInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\x93\x01\n" +
	"\x16GetAllInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"u\n" +
	"\x1dCreateInvoiceSignatureRequest\x12T\n" +
	"\apayload\x18\x01 \x01(\v2:.fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayloadR\apayload\"\xb4\x01\n" +
	"$CreateInvoiceSignatureRequestPayload\x12=\n" +
	"\finvoice_hash\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\vinvoiceHash\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"0\n" +
	"\x1eCreateInvoiceSignatureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x14CreateInvoiceRequest\x12K\n" +
	"\apayload\x18\x01 \x01(\v21.fractalengine.rpc.v1.CreateInvoiceRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\x90\x03\n" +
	"\x1bCreateInvoiceRequestPayload\x12O\n" +
	"\x0fpayment_address\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\x0epaymentAddress\x12K\n" +
	"\rbuyer_address\x18\x02 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\fbuyerAddress\x12@\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\bmintHash\x12#\n" +
	"\bquantity\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\x12M\n" +
	"\x0eseller_address\x18\x06 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\rsellerAddress\"\x81\x01\n" +
	"\x15CreateInvoiceResponse\x12.\n" +
	"\x04hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hash\x128\n" +
	"\x18encoded_transaction_body\x18\x02 \x01(\tR\x16encodedTransactionBodyB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\beditionsp\xe8\a"

var file_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_invoices_proto_goTypes = []any{
	(*GetInvoicesRequest)(nil),                   // 0: fractalengine.rpc.v1.GetInvoicesRequest
	(*GetAllInvoicesRequest)(nil),                // 1: fractalengine.rpc.v1.GetAllInvoicesRequest
	(*GetInvoicesResponse)(nil),                  // 2: fractalengine.rpc.v1.GetInvoicesResponse
	(*GetAllInvoicesResponse)(nil),               // 3: fractalengine.rpc.v1.GetAllInvoicesResponse
	(*CreateInvoiceSignatureRequest)(nil),        // 4: fractalengine.rpc.v1.CreateInvoiceSignatureRequest
	(*CreateInvoiceSignatureRequestPayload)(nil), // 5: fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	(*CreateInvoiceSignatureResponse)(nil),       // 6: fractalengine.rpc.v1.CreateInvoiceSignatureResponse
	(*CreateInvoiceRequest)(nil),                 // 7: fractalengine.rpc.v1.CreateInvoiceRequest
	(*CreateInvoiceRequestPayload)(nil),          // 8: fractalengine.rpc.v1.CreateInvoiceRequestPayload
	(*CreateInvoiceResponse)(nil),                // 9: fractalengine.rpc.v1.CreateInvoiceResponse
	(*Address)(nil),                              // 10: fractalengine.rpc.v1.Address
	(*wrapperspb.Int32Value)(nil),                // 11: google.protobuf.Int32Value
	(*Hash)(nil),                                 // 12: fractalengine.rpc.v1.Hash
	(*Invoice)(nil),                              // 13: fractalengine.rpc.v1.Invoice
}
var file_invoices_proto_depIdxs = []int32{
	10, // 0: fractalengine.rpc.v1.GetInvoicesRequest.address:type_name -> fractalengine.rpc.v1.Address
	11, // 1: fractalengine.rpc.v1.GetInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	11, // 2: fractalengine.rpc.v1.GetInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	12, // 3: fractalengine.rpc.v1.GetInvoicesRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	11, // 4: fractalengine.rpc.v1.GetAllInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	11, // 5: fractalengine.rpc.v1.GetAllInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	12, // 6: fractalengine.rpc.v1.GetAllInvoicesRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	13, // 7: fractalengine.rpc.v1.GetInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	13, // 8: fractalengine.rpc.v1.GetAllInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	5,  // 9: fractalengine.rpc.v1.CreateInvoiceSignatureRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	8,  // 10: fractalengine.rpc.v1.CreateInvoiceRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceRequestPayload
	10, // 11: fractalengine.rpc.v1.CreateInvoiceRequestPayload.payment_address:type_name -> fractalengine.rpc.v1.Address
	10, // 12: fractalengine.rpc.v1.CreateInvoiceRequestPayload.buyer_address:type_name -> fractalengine.rpc.v1.Address
	12, // 13: fractalengine.rpc.v1.CreateInvoiceRequestPayload.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	10, // 14: fractalengine.rpc.v1.CreateInvoiceRequestPayload.seller_address:type_name -> fractalengine.rpc.v1.Address
	12, // 15: fractalengine.rpc.v1.CreateInvoiceResponse.hash:type_name -> fractalengine.rpc.v1.Hash
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_invoices_proto_init() }
func file_invoices_proto_init() {
	if File_invoices_proto != nil {
		return
	}
	file_common_proto_init()
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoices_proto_goTypes,
		DependencyIndexes: file_invoices_proto_depIdxs,
		MessageInfos:      file_invoices_proto_msgTypes,
	}.Build()
	File_invoices_proto = out.File
	file_invoices_proto_goTypes = nil
	file_invoices_proto_depIdxs = nil
}
