// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoices.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit         *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	MintHash      *Hash                  `protobuf:"bytes,4,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesRequest) Reset() {
	*x = GetInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesRequest) ProtoMessage() {}

func (x *GetInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesRequest.ProtoReflect.Descriptor instead.
func (*GetInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{0}
}

func (x *GetInvoicesRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetInvoicesRequest) GetMintHash() *Hash {
	if x != nil {
		return x.MintHash
	}
	return nil
}

type GetAllInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	MintHash      *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesRequest) Reset() {
	*x = GetAllInvoicesRequest{}
	mi := &file_invoices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesRequest) ProtoMessage() {}

func (x *GetAllInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesRequest.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllInvoicesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetAllInvoicesRequest) GetMintHash() *Hash {
	if x != nil {
		return x.MintHash
	}
	return nil
}

type GetInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesResponse) Reset() {
	*x = GetInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesResponse) ProtoMessage() {}

func (x *GetInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{2}
}

func (x *GetInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *GetInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	mi := &file_invoices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *GetAllInvoicesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllInvoicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateInvoiceSignatureRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Payload       *CreateInvoiceSignatureRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequest) Reset() {
	*x = CreateInvoiceSignatureRequest{}
	mi := &file_invoices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequest) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceSignatureRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceSignatureRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInvoiceSignatureRequest) GetPayload() *CreateInvoiceSignatureRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateInvoiceSignatureRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceHash   string                 `protobuf:"bytes,1,opt,name=invoice_hash,json=invoiceHash,proto3" json:"invoice_hash,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureRequestPayload) Reset() {
	*x = CreateInvoiceSignatureRequestPayload{}
	mi := &file_invoices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceSignatureRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceSignatureRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateInvoiceSignatureRequestPayload) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInvoiceSignatureRequestPayload) GetInvoiceHash() string {
	if x != nil {
		return x.InvoiceHash
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateInvoiceSignatureRequestPayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateInvoiceSignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceSignatureResponse) Reset() {
	*x = CreateInvoiceSignatureResponse{}
	mi := &file_invoices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceSignatureResponse) ProtoMessage() {}

func (x *CreateInvoiceSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceSignatureResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceSignatureResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInvoiceSignatureResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateInvoiceRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Payload       *CreateInvoiceRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                       `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                       `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_invoices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInvoiceRequest) GetPayload() *CreateInvoiceRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateInvoiceRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateInvoiceRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateInvoiceRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentAddress *Address               `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	BuyerAddress   *Address               `protobuf:"bytes,2,opt,name=buyer_address,json=buyerAddress,proto3" json:"buyer_address,omitempty"`
	MintHash       *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	SellerAddress  *Address               `protobuf:"bytes,6,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInvoiceRequestPayload) Reset() {
	*x = CreateInvoiceRequestPayload{}
	mi := &file_invoices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequestPayload) ProtoMessage() {}

func (x *CreateInvoiceRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequestPayload) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInvoiceRequestPayload) GetPaymentAddress() *Address {
	if x != nil {
		return x.PaymentAddress
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetBuyerAddress() *Address {
	if x != nil {
		return x.BuyerAddress
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetMintHash() *Hash {
	if x != nil {
		return x.MintHash
	}
	return nil
}

func (x *CreateInvoiceRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateInvoiceRequestPayload) GetSellerAddress() *Address {
	if x != nil {
		return x.SellerAddress
	}
	return nil
}

type CreateInvoiceResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Hash                   *Hash                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	EncodedTransactionBody string                 `protobuf:"bytes,2,opt,name=encoded_transaction_body,json=encodedTransactionBody,proto3" json:"encoded_transaction_body,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_invoices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoices_proto_rawDescGZIP(), []int{9}
}

func (x *CreateInvoiceResponse) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CreateInvoiceResponse) GetEncodedTransactionBody() string {
	if x != nil {
		return x.EncodedTransactionBody
	}
	return ""
}

var File_invoices_proto protoreflect.FileDescriptor

const file_invoices_proto_rawDesc = "" +
	"\n" +
	"\x0einvoices.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\x1a\vtypes.proto\"\xea\x01\n" +
	"\x12GetInvoicesRequest\x127\n" +
	"\aaddress\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\aaddress\x121\n" +
	"\x05limit\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x04 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\"\xb4\x01\n" +
	"\x15GetAllInvoicesRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\"\x90\x01\n" +
	"\x13GetInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\x93\x01\n" +
	"\x16GetAllInvoicesResponse\x129\n" +
	"\binvoices\x18\x01 \x03(\v2\x1d.fractalengine.rpc.v1.InvoiceR\binvoices\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"u\n" +
	"\x1dCreateInvoiceSignatureRequest\x12T\n" +
	"\apayload\x18\x01 \x01(\v2:.fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayloadR\apayload\"\xb4\x01\n" +
	"$CreateInvoiceSignatureRequestPayload\x12=\n" +
	"\finvoice_hash\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\vinvoiceHash\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"0\n" +
	"\x1eCreateInvoiceSignatureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x14CreateInvoiceRequest\x12K\n" +
	"\apayload\x18\x01 \x01(\v21.fractalengine.rpc.v1.CreateInvoiceRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\x90\x03\n" +
	"\x1bCreateInvoiceRequestPayload\x12O\n" +
	"\x0fpayment_address\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\x0epaymentAddress\x12K\n" +
	"\rbuyer_address\x18\x02 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\fbuyerAddress\x12@\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\bmintHash\x12#\n" +
	"\bquantity\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\x12M\n" +
	"\x0eseller_address\x18\x06 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\rsellerAddress\"\x81\x01\n" +
	"\x15CreateInvoiceResponse\x12.\n" +
	"\x04hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hash\x128\n" +
	"\x18encoded_transaction_body\x18\x02 \x01(\tR\x16encodedTransactionBodyB\x12Z\x10pkg/rpc/protocolb\x06proto3"

var (
	file_invoices_proto_rawDescOnce sync.Once
	file_invoices_proto_rawDescData []byte
)

func file_invoices_proto_rawDescGZIP() []byte {
	file_invoices_proto_rawDescOnce.Do(func() {
		file_invoices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)))
	})
	return file_invoices_proto_rawDescData
}

var file_invoices_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_invoices_proto_goTypes = []any{
	(*GetInvoicesRequest)(nil),                   // 0: fractalengine.rpc.v1.GetInvoicesRequest
	(*GetAllInvoicesRequest)(nil),                // 1: fractalengine.rpc.v1.GetAllInvoicesRequest
	(*GetInvoicesResponse)(nil),                  // 2: fractalengine.rpc.v1.GetInvoicesResponse
	(*GetAllInvoicesResponse)(nil),               // 3: fractalengine.rpc.v1.GetAllInvoicesResponse
	(*CreateInvoiceSignatureRequest)(nil),        // 4: fractalengine.rpc.v1.CreateInvoiceSignatureRequest
	(*CreateInvoiceSignatureRequestPayload)(nil), // 5: fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	(*CreateInvoiceSignatureResponse)(nil),       // 6: fractalengine.rpc.v1.CreateInvoiceSignatureResponse
	(*CreateInvoiceRequest)(nil),                 // 7: fractalengine.rpc.v1.CreateInvoiceRequest
	(*CreateInvoiceRequestPayload)(nil),          // 8: fractalengine.rpc.v1.CreateInvoiceRequestPayload
	(*CreateInvoiceResponse)(nil),                // 9: fractalengine.rpc.v1.CreateInvoiceResponse
	(*Address)(nil),                              // 10: fractalengine.rpc.v1.Address
	(*wrapperspb.Int32Value)(nil),                // 11: google.protobuf.Int32Value
	(*Hash)(nil),                                 // 12: fractalengine.rpc.v1.Hash
	(*Invoice)(nil),                              // 13: fractalengine.rpc.v1.Invoice
}
var file_invoices_proto_depIdxs = []int32{
	10, // 0: fractalengine.rpc.v1.GetInvoicesRequest.address:type_name -> fractalengine.rpc.v1.Address
	11, // 1: fractalengine.rpc.v1.GetInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	11, // 2: fractalengine.rpc.v1.GetInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	12, // 3: fractalengine.rpc.v1.GetInvoicesRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	11, // 4: fractalengine.rpc.v1.GetAllInvoicesRequest.limit:type_name -> google.protobuf.Int32Value
	11, // 5: fractalengine.rpc.v1.GetAllInvoicesRequest.page:type_name -> google.protobuf.Int32Value
	12, // 6: fractalengine.rpc.v1.GetAllInvoicesRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	13, // 7: fractalengine.rpc.v1.GetInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	13, // 8: fractalengine.rpc.v1.GetAllInvoicesResponse.invoices:type_name -> fractalengine.rpc.v1.Invoice
	5,  // 9: fractalengine.rpc.v1.CreateInvoiceSignatureRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceSignatureRequestPayload
	8,  // 10: fractalengine.rpc.v1.CreateInvoiceRequest.payload:type_name -> fractalengine.rpc.v1.CreateInvoiceRequestPayload
	10, // 11: fractalengine.rpc.v1.CreateInvoiceRequestPayload.payment_address:type_name -> fractalengine.rpc.v1.Address
	10, // 12: fractalengine.rpc.v1.CreateInvoiceRequestPayload.buyer_address:type_name -> fractalengine.rpc.v1.Address
	12, // 13: fractalengine.rpc.v1.CreateInvoiceRequestPayload.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	10, // 14: fractalengine.rpc.v1.CreateInvoiceRequestPayload.seller_address:type_name -> fractalengine.rpc.v1.Address
	12, // 15: fractalengine.rpc.v1.CreateInvoiceResponse.hash:type_name -> fractalengine.rpc.v1.Hash
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_invoices_proto_init() }
func file_invoices_proto_init() {
	if File_invoices_proto != nil {
		return
	}
	file_common_proto_init()
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoices_proto_rawDesc), len(file_invoices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoices_proto_goTypes,
		DependencyIndexes: file_invoices_proto_depIdxs,
		MessageInfos:      file_invoices_proto_msgTypes,
	}.Build()
	File_invoices_proto = out.File
	file_invoices_proto_goTypes = nil
	file_invoices_proto_depIdxs = nil
}
