// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mints.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMintsRequest) Reset() {
	*x = GetMintsRequest{}
	mi := &file_mints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMintsRequest) ProtoMessage() {}

func (x *GetMintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMintsRequest.ProtoReflect.Descriptor instead.
func (*GetMintsRequest) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{0}
}

func (x *GetMintsRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetMintsRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetMintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *Hash                  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMintRequest) Reset() {
	*x = GetMintRequest{}
	mi := &file_mints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMintRequest) ProtoMessage() {}

func (x *GetMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMintRequest.ProtoReflect.Descriptor instead.
func (*GetMintRequest) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{1}
}

func (x *GetMintRequest) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetMintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Mints         []*Mint                `protobuf:"bytes,2,rep,name=mints,proto3" json:"mints,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMintsResponse) Reset() {
	*x = GetMintsResponse{}
	mi := &file_mints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMintsResponse) ProtoMessage() {}

func (x *GetMintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMintsResponse.ProtoReflect.Descriptor instead.
func (*GetMintsResponse) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{2}
}

func (x *GetMintsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMintsResponse) GetMints() []*Mint {
	if x != nil {
		return x.Mints
	}
	return nil
}

func (x *GetMintsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMintsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mint          *Mint                  `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMintResponse) Reset() {
	*x = GetMintResponse{}
	mi := &file_mints_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMintResponse) ProtoMessage() {}

func (x *GetMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMintResponse.ProtoReflect.Descriptor instead.
func (*GetMintResponse) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{3}
}

func (x *GetMintResponse) GetMint() *Mint {
	if x != nil {
		return x.Mint
	}
	return nil
}

type CreateMintRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Payload       *CreateMintRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                    `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                    `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMintRequest) Reset() {
	*x = CreateMintRequest{}
	mi := &file_mints_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMintRequest) ProtoMessage() {}

func (x *CreateMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMintRequest.ProtoReflect.Descriptor instead.
func (*CreateMintRequest) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMintRequest) GetPayload() *CreateMintRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateMintRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateMintRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateMintRequestPayload struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	AssetManagers            []*AssetManager          `protobuf:"bytes,1,rep,name=asset_managers,json=assetManagers,proto3" json:"asset_managers,omitempty"`
	ContractOfSale           string                   `protobuf:"bytes,2,opt,name=contract_of_sale,json=contractOfSale,proto3" json:"contract_of_sale,omitempty"`
	Description              string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FeedUrl                  string                   `protobuf:"bytes,4,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	FractionCount            int32                    `protobuf:"varint,5,opt,name=fraction_count,json=fractionCount,proto3" json:"fraction_count,omitempty"`
	LockupOptions            *StringInterfaceMap      `protobuf:"bytes,6,opt,name=lockup_options,json=lockupOptions,proto3" json:"lockup_options,omitempty"`
	Metadata                 *StringInterfaceMap      `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MinSignatures            int32                    `protobuf:"varint,8,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	OwnerAddress             *Address                 `protobuf:"bytes,9,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Requirements             *StringInterfaceMap      `protobuf:"bytes,10,opt,name=requirements,proto3" json:"requirements,omitempty"`
	SignatureRequirementType SignatureRequirementType `protobuf:"varint,11,opt,name=signature_requirement_type,json=signatureRequirementType,proto3,enum=fractalengine.rpc.v1.SignatureRequirementType" json:"signature_requirement_type,omitempty"`
	Tags                     []string                 `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Title                    string                   `protobuf:"bytes,13,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateMintRequestPayload) Reset() {
	*x = CreateMintRequestPayload{}
	mi := &file_mints_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMintRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMintRequestPayload) ProtoMessage() {}

func (x *CreateMintRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMintRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateMintRequestPayload) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMintRequestPayload) GetAssetManagers() []*AssetManager {
	if x != nil {
		return x.AssetManagers
	}
	return nil
}

func (x *CreateMintRequestPayload) GetContractOfSale() string {
	if x != nil {
		return x.ContractOfSale
	}
	return ""
}

func (x *CreateMintRequestPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMintRequestPayload) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *CreateMintRequestPayload) GetFractionCount() int32 {
	if x != nil {
		return x.FractionCount
	}
	return 0
}

func (x *CreateMintRequestPayload) GetLockupOptions() *StringInterfaceMap {
	if x != nil {
		return x.LockupOptions
	}
	return nil
}

func (x *CreateMintRequestPayload) GetMetadata() *StringInterfaceMap {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateMintRequestPayload) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

func (x *CreateMintRequestPayload) GetOwnerAddress() *Address {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *CreateMintRequestPayload) GetRequirements() *StringInterfaceMap {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CreateMintRequestPayload) GetSignatureRequirementType() SignatureRequirementType {
	if x != nil {
		return x.SignatureRequirementType
	}
	return SignatureRequirementType_SIGNATURE_REQUIREMENT_TYPE_UNSPECIFIED
}

func (x *CreateMintRequestPayload) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateMintRequestPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateMintResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EncodedTransactionBody string                 `protobuf:"bytes,1,opt,name=encoded_transaction_body,json=encodedTransactionBody,proto3" json:"encoded_transaction_body,omitempty"`
	Hash                   *Hash                  `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateMintResponse) Reset() {
	*x = CreateMintResponse{}
	mi := &file_mints_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMintResponse) ProtoMessage() {}

func (x *CreateMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mints_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMintResponse.ProtoReflect.Descriptor instead.
func (*CreateMintResponse) Descriptor() ([]byte, []int) {
	return file_mints_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMintResponse) GetEncodedTransactionBody() string {
	if x != nil {
		return x.EncodedTransactionBody
	}
	return ""
}

func (x *CreateMintResponse) GetHash() *Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_mints_proto protoreflect.FileDescriptor

const file_mints_proto_rawDesc = "" +
	"\n" +
	"\vmints.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\x1a\vtypes.proto\"u\n" +
	"\x0fGetMintsRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\"@\n" +
	"\x0eGetMintRequest\x12.\n" +
	"\x04hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hash\"\x84\x01\n" +
	"\x10GetMintsResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x120\n" +
	"\x05mints\x18\x02 \x03(\v2\x1a.fractalengine.rpc.v1.MintR\x05mints\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"A\n" +
	"\x0fGetMintResponse\x12.\n" +
	"\x04mint\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.MintR\x04mint\"\x9a\x01\n" +
	"\x11CreateMintRequest\x12H\n" +
	"\apayload\x18\x01 \x01(\v2..fractalengine.rpc.v1.CreateMintRequestPayloadR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"\xf6\x05\n" +
	"\x18CreateMintRequestPayload\x12I\n" +
	"\x0easset_managers\x18\x01 \x03(\v2\".fractalengine.rpc.v1.AssetManagerR\rassetManagers\x12(\n" +
	"\x10contract_of_sale\x18\x02 \x01(\tR\x0econtractOfSale\x12)\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12\x19\n" +
	"\bfeed_url\x18\x04 \x01(\tR\afeedUrl\x12.\n" +
	"\x0efraction_count\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\rfractionCount\x12O\n" +
	"\x0elockup_options\x18\x06 \x01(\v2(.fractalengine.rpc.v1.StringInterfaceMapR\rlockupOptions\x12D\n" +
	"\bmetadata\x18\a \x01(\v2(.fractalengine.rpc.v1.StringInterfaceMapR\bmetadata\x12%\n" +
	"\x0emin_signatures\x18\b \x01(\x05R\rminSignatures\x12B\n" +
	"\rowner_address\x18\t \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\fownerAddress\x12L\n" +
	"\frequirements\x18\n" +
	" \x01(\v2(.fractalengine.rpc.v1.StringInterfaceMapR\frequirements\x12l\n" +
	"\x1asignature_requirement_type\x18\v \x01(\x0e2..fractalengine.rpc.v1.SignatureRequirementTypeR\x18signatureRequirementType\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1d\n" +
	"\x05title\x18\r \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\"~\n" +
	"\x12CreateMintResponse\x128\n" +
	"\x18encoded_transaction_body\x18\x01 \x01(\tR\x16encodedTransactionBody\x12.\n" +
	"\x04hash\x18\x02 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hashB\x12Z\x10pkg/rpc/protocolb\x06proto3"

var (
	file_mints_proto_rawDescOnce sync.Once
	file_mints_proto_rawDescData []byte
)

func file_mints_proto_rawDescGZIP() []byte {
	file_mints_proto_rawDescOnce.Do(func() {
		file_mints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mints_proto_rawDesc), len(file_mints_proto_rawDesc)))
	})
	return file_mints_proto_rawDescData
}

var file_mints_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mints_proto_goTypes = []any{
	(*GetMintsRequest)(nil),          // 0: fractalengine.rpc.v1.GetMintsRequest
	(*GetMintRequest)(nil),           // 1: fractalengine.rpc.v1.GetMintRequest
	(*GetMintsResponse)(nil),         // 2: fractalengine.rpc.v1.GetMintsResponse
	(*GetMintResponse)(nil),          // 3: fractalengine.rpc.v1.GetMintResponse
	(*CreateMintRequest)(nil),        // 4: fractalengine.rpc.v1.CreateMintRequest
	(*CreateMintRequestPayload)(nil), // 5: fractalengine.rpc.v1.CreateMintRequestPayload
	(*CreateMintResponse)(nil),       // 6: fractalengine.rpc.v1.CreateMintResponse
	(*wrapperspb.Int32Value)(nil),    // 7: google.protobuf.Int32Value
	(*Hash)(nil),                     // 8: fractalengine.rpc.v1.Hash
	(*Mint)(nil),                     // 9: fractalengine.rpc.v1.Mint
	(*AssetManager)(nil),             // 10: fractalengine.rpc.v1.AssetManager
	(*StringInterfaceMap)(nil),       // 11: fractalengine.rpc.v1.StringInterfaceMap
	(*Address)(nil),                  // 12: fractalengine.rpc.v1.Address
	(SignatureRequirementType)(0),    // 13: fractalengine.rpc.v1.SignatureRequirementType
}
var file_mints_proto_depIdxs = []int32{
	7,  // 0: fractalengine.rpc.v1.GetMintsRequest.limit:type_name -> google.protobuf.Int32Value
	7,  // 1: fractalengine.rpc.v1.GetMintsRequest.page:type_name -> google.protobuf.Int32Value
	8,  // 2: fractalengine.rpc.v1.GetMintRequest.hash:type_name -> fractalengine.rpc.v1.Hash
	9,  // 3: fractalengine.rpc.v1.GetMintsResponse.mints:type_name -> fractalengine.rpc.v1.Mint
	9,  // 4: fractalengine.rpc.v1.GetMintResponse.mint:type_name -> fractalengine.rpc.v1.Mint
	5,  // 5: fractalengine.rpc.v1.CreateMintRequest.payload:type_name -> fractalengine.rpc.v1.CreateMintRequestPayload
	10, // 6: fractalengine.rpc.v1.CreateMintRequestPayload.asset_managers:type_name -> fractalengine.rpc.v1.AssetManager
	11, // 7: fractalengine.rpc.v1.CreateMintRequestPayload.lockup_options:type_name -> fractalengine.rpc.v1.StringInterfaceMap
	11, // 8: fractalengine.rpc.v1.CreateMintRequestPayload.metadata:type_name -> fractalengine.rpc.v1.StringInterfaceMap
	12, // 9: fractalengine.rpc.v1.CreateMintRequestPayload.owner_address:type_name -> fractalengine.rpc.v1.Address
	11, // 10: fractalengine.rpc.v1.CreateMintRequestPayload.requirements:type_name -> fractalengine.rpc.v1.StringInterfaceMap
	13, // 11: fractalengine.rpc.v1.CreateMintRequestPayload.signature_requirement_type:type_name -> fractalengine.rpc.v1.SignatureRequirementType
	8,  // 12: fractalengine.rpc.v1.CreateMintResponse.hash:type_name -> fractalengine.rpc.v1.Hash
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_mints_proto_init() }
func file_mints_proto_init() {
	if File_mints_proto != nil {
		return
	}
	file_common_proto_init()
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mints_proto_rawDesc), len(file_mints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mints_proto_goTypes,
		DependencyIndexes: file_mints_proto_depIdxs,
		MessageInfos:      file_mints_proto_msgTypes,
	}.Build()
	File_mints_proto = out.File
	file_mints_proto_goTypes = nil
	file_mints_proto_depIdxs = nil
}
