// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: offers.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSellOfferResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Hash        *Hash                  `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateSellOfferResponse) Reset() {
	*x = CreateSellOfferResponse{}
	mi := &file_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferResponse) ProtoMessage() {}

func (x *CreateSellOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSellOfferResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateSellOfferResponse) GetHash() *Hash {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *CreateSellOfferResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateSellOfferResponse) SetHash(v *Hash) {
	x.xxx_hidden_Hash = v
}

func (x *CreateSellOfferResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateSellOfferResponse) HasHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hash != nil
}

func (x *CreateSellOfferResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CreateSellOfferResponse) ClearHash() {
	x.xxx_hidden_Hash = nil
}

type CreateSellOfferResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *string
	Hash *Hash
}

func (b0 CreateSellOfferResponse_builder) Build() *CreateSellOfferResponse {
	m0 := &CreateSellOfferResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Hash = b.Hash
	return m0
}

type CreateBuyOfferResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Hash        *Hash                  `protobuf:"bytes,2,opt,name=hash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateBuyOfferResponse) Reset() {
	*x = CreateBuyOfferResponse{}
	mi := &file_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferResponse) ProtoMessage() {}

func (x *CreateBuyOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBuyOfferResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateBuyOfferResponse) GetHash() *Hash {
	if x != nil {
		return x.xxx_hidden_Hash
	}
	return nil
}

func (x *CreateBuyOfferResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateBuyOfferResponse) SetHash(v *Hash) {
	x.xxx_hidden_Hash = v
}

func (x *CreateBuyOfferResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateBuyOfferResponse) HasHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hash != nil
}

func (x *CreateBuyOfferResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CreateBuyOfferResponse) ClearHash() {
	x.xxx_hidden_Hash = nil
}

type CreateBuyOfferResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   *string
	Hash *Hash
}

func (b0 CreateBuyOfferResponse_builder) Build() *CreateBuyOfferResponse {
	m0 := &CreateBuyOfferResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Hash = b.Hash
	return m0
}

type GetSellOffersRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit"`
	xxx_hidden_Page           *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_MintHash       *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash"`
	xxx_hidden_OffererAddress *Address               `protobuf:"bytes,4,opt,name=offerer_address,json=offererAddress"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetSellOffersRequest) Reset() {
	*x = GetSellOffersRequest{}
	mi := &file_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellOffersRequest) ProtoMessage() {}

func (x *GetSellOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSellOffersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetSellOffersRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetSellOffersRequest) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetSellOffersRequest) GetOffererAddress() *Address {
	if x != nil {
		return x.xxx_hidden_OffererAddress
	}
	return nil
}

func (x *GetSellOffersRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetSellOffersRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetSellOffersRequest) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *GetSellOffersRequest) SetOffererAddress(v *Address) {
	x.xxx_hidden_OffererAddress = v
}

func (x *GetSellOffersRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetSellOffersRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetSellOffersRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetSellOffersRequest) HasOffererAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OffererAddress != nil
}

func (x *GetSellOffersRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetSellOffersRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetSellOffersRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

func (x *GetSellOffersRequest) ClearOffererAddress() {
	x.xxx_hidden_OffererAddress = nil
}

type GetSellOffersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit          *wrapperspb.Int32Value
	Page           *wrapperspb.Int32Value
	MintHash       *Hash
	OffererAddress *Address
}

func (b0 GetSellOffersRequest_builder) Build() *GetSellOffersRequest {
	m0 := &GetSellOffersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	x.xxx_hidden_OffererAddress = b.OffererAddress
	return m0
}

type GetBuyOffersRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Limit         *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=limit"`
	xxx_hidden_Page          *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=page"`
	xxx_hidden_MintHash      *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash"`
	xxx_hidden_SellerAddress *Address               `protobuf:"bytes,4,opt,name=seller_address,json=sellerAddress"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetBuyOffersRequest) Reset() {
	*x = GetBuyOffersRequest{}
	mi := &file_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOffersRequest) ProtoMessage() {}

func (x *GetBuyOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBuyOffersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return nil
}

func (x *GetBuyOffersRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return nil
}

func (x *GetBuyOffersRequest) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *GetBuyOffersRequest) GetSellerAddress() *Address {
	if x != nil {
		return x.xxx_hidden_SellerAddress
	}
	return nil
}

func (x *GetBuyOffersRequest) SetLimit(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Limit = v
}

func (x *GetBuyOffersRequest) SetPage(v *wrapperspb.Int32Value) {
	x.xxx_hidden_Page = v
}

func (x *GetBuyOffersRequest) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *GetBuyOffersRequest) SetSellerAddress(v *Address) {
	x.xxx_hidden_SellerAddress = v
}

func (x *GetBuyOffersRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limit != nil
}

func (x *GetBuyOffersRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Page != nil
}

func (x *GetBuyOffersRequest) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *GetBuyOffersRequest) HasSellerAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SellerAddress != nil
}

func (x *GetBuyOffersRequest) ClearLimit() {
	x.xxx_hidden_Limit = nil
}

func (x *GetBuyOffersRequest) ClearPage() {
	x.xxx_hidden_Page = nil
}

func (x *GetBuyOffersRequest) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

func (x *GetBuyOffersRequest) ClearSellerAddress() {
	x.xxx_hidden_SellerAddress = nil
}

type GetBuyOffersRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Limit         *wrapperspb.Int32Value
	Page          *wrapperspb.Int32Value
	MintHash      *Hash
	SellerAddress *Address
}

func (b0 GetBuyOffersRequest_builder) Build() *GetBuyOffersRequest {
	m0 := &GetBuyOffersRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Page = b.Page
	x.xxx_hidden_MintHash = b.MintHash
	x.xxx_hidden_SellerAddress = b.SellerAddress
	return m0
}

type GetSellOffersResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offers      *[]*SellOfferWithMint  `protobuf:"bytes,1,rep,name=offers"`
	xxx_hidden_Total       int32                  `protobuf:"varint,2,opt,name=total"`
	xxx_hidden_Page        int32                  `protobuf:"varint,3,opt,name=page"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,4,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSellOffersResponse) Reset() {
	*x = GetSellOffersResponse{}
	mi := &file_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellOffersResponse) ProtoMessage() {}

func (x *GetSellOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSellOffersResponse) GetOffers() []*SellOfferWithMint {
	if x != nil {
		if x.xxx_hidden_Offers != nil {
			return *x.xxx_hidden_Offers
		}
	}
	return nil
}

func (x *GetSellOffersResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetSellOffersResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetSellOffersResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetSellOffersResponse) SetOffers(v []*SellOfferWithMint) {
	x.xxx_hidden_Offers = &v
}

func (x *GetSellOffersResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GetSellOffersResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GetSellOffersResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *GetSellOffersResponse) HasTotal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetSellOffersResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetSellOffersResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetSellOffersResponse) ClearTotal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Total = 0
}

func (x *GetSellOffersResponse) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Page = 0
}

func (x *GetSellOffersResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Limit = 0
}

type GetSellOffersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offers []*SellOfferWithMint
	Total  *int32
	Page   *int32
	Limit  *int32
}

func (b0 GetSellOffersResponse_builder) Build() *GetSellOffersResponse {
	m0 := &GetSellOffersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Offers = &b.Offers
	if b.Total != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Total = *b.Total
	}
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Page = *b.Page
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type GetBuyOffersResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offers      *[]*BuyOfferWithMint   `protobuf:"bytes,1,rep,name=offers"`
	xxx_hidden_Total       int32                  `protobuf:"varint,2,opt,name=total"`
	xxx_hidden_Page        int32                  `protobuf:"varint,3,opt,name=page"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,4,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetBuyOffersResponse) Reset() {
	*x = GetBuyOffersResponse{}
	mi := &file_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOffersResponse) ProtoMessage() {}

func (x *GetBuyOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBuyOffersResponse) GetOffers() []*BuyOfferWithMint {
	if x != nil {
		if x.xxx_hidden_Offers != nil {
			return *x.xxx_hidden_Offers
		}
	}
	return nil
}

func (x *GetBuyOffersResponse) GetTotal() int32 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *GetBuyOffersResponse) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *GetBuyOffersResponse) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GetBuyOffersResponse) SetOffers(v []*BuyOfferWithMint) {
	x.xxx_hidden_Offers = &v
}

func (x *GetBuyOffersResponse) SetTotal(v int32) {
	x.xxx_hidden_Total = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *GetBuyOffersResponse) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *GetBuyOffersResponse) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *GetBuyOffersResponse) HasTotal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetBuyOffersResponse) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetBuyOffersResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetBuyOffersResponse) ClearTotal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Total = 0
}

func (x *GetBuyOffersResponse) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Page = 0
}

func (x *GetBuyOffersResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Limit = 0
}

type GetBuyOffersResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offers []*BuyOfferWithMint
	Total  *int32
	Page   *int32
	Limit  *int32
}

func (b0 GetBuyOffersResponse_builder) Build() *GetBuyOffersResponse {
	m0 := &GetBuyOffersResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Offers = &b.Offers
	if b.Total != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Total = *b.Total
	}
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Page = *b.Page
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type CreateSellOfferRequest struct {
	state                  protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Payload     *CreateSellOfferRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	xxx_hidden_PublicKey   *string                        `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                        `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateSellOfferRequest) Reset() {
	*x = CreateSellOfferRequest{}
	mi := &file_offers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferRequest) ProtoMessage() {}

func (x *CreateSellOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSellOfferRequest) GetPayload() *CreateSellOfferRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateSellOfferRequest) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *CreateSellOfferRequest) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *CreateSellOfferRequest) SetPayload(v *CreateSellOfferRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateSellOfferRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateSellOfferRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateSellOfferRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateSellOfferRequest) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateSellOfferRequest) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateSellOfferRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *CreateSellOfferRequest) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *CreateSellOfferRequest) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type CreateSellOfferRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *CreateSellOfferRequestPayload
	PublicKey *string
	Signature *string
}

func (b0 CreateSellOfferRequest_builder) Build() *CreateSellOfferRequest {
	m0 := &CreateSellOfferRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type CreateSellOfferRequestPayload struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OffererAddress *Address               `protobuf:"bytes,1,opt,name=offerer_address,json=offererAddress"`
	xxx_hidden_MintHash       *Hash                  `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash"`
	xxx_hidden_Quantity       int32                  `protobuf:"varint,3,opt,name=quantity"`
	xxx_hidden_Price          int32                  `protobuf:"varint,4,opt,name=price"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateSellOfferRequestPayload) Reset() {
	*x = CreateSellOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferRequestPayload) ProtoMessage() {}

func (x *CreateSellOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSellOfferRequestPayload) GetOffererAddress() *Address {
	if x != nil {
		return x.xxx_hidden_OffererAddress
	}
	return nil
}

func (x *CreateSellOfferRequestPayload) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *CreateSellOfferRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *CreateSellOfferRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.xxx_hidden_Price
	}
	return 0
}

func (x *CreateSellOfferRequestPayload) SetOffererAddress(v *Address) {
	x.xxx_hidden_OffererAddress = v
}

func (x *CreateSellOfferRequestPayload) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *CreateSellOfferRequestPayload) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *CreateSellOfferRequestPayload) SetPrice(v int32) {
	x.xxx_hidden_Price = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *CreateSellOfferRequestPayload) HasOffererAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OffererAddress != nil
}

func (x *CreateSellOfferRequestPayload) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *CreateSellOfferRequestPayload) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateSellOfferRequestPayload) HasPrice() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateSellOfferRequestPayload) ClearOffererAddress() {
	x.xxx_hidden_OffererAddress = nil
}

func (x *CreateSellOfferRequestPayload) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

func (x *CreateSellOfferRequestPayload) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Quantity = 0
}

func (x *CreateSellOfferRequestPayload) ClearPrice() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Price = 0
}

type CreateSellOfferRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OffererAddress *Address
	MintHash       *Hash
	Quantity       *int32
	Price          *int32
}

func (b0 CreateSellOfferRequestPayload_builder) Build() *CreateSellOfferRequestPayload {
	m0 := &CreateSellOfferRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OffererAddress = b.OffererAddress
	x.xxx_hidden_MintHash = b.MintHash
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	if b.Price != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Price = *b.Price
	}
	return m0
}

type CreateBuyOfferRequest struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Payload     *CreateBuyOfferRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	xxx_hidden_PublicKey   *string                       `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                       `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateBuyOfferRequest) Reset() {
	*x = CreateBuyOfferRequest{}
	mi := &file_offers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferRequest) ProtoMessage() {}

func (x *CreateBuyOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBuyOfferRequest) GetPayload() *CreateBuyOfferRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *CreateBuyOfferRequest) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *CreateBuyOfferRequest) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *CreateBuyOfferRequest) SetPayload(v *CreateBuyOfferRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *CreateBuyOfferRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CreateBuyOfferRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CreateBuyOfferRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *CreateBuyOfferRequest) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateBuyOfferRequest) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateBuyOfferRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *CreateBuyOfferRequest) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *CreateBuyOfferRequest) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type CreateBuyOfferRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *CreateBuyOfferRequestPayload
	PublicKey *string
	Signature *string
}

func (b0 CreateBuyOfferRequest_builder) Build() *CreateBuyOfferRequest {
	m0 := &CreateBuyOfferRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type CreateBuyOfferRequestPayload struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OffererAddress *Address               `protobuf:"bytes,1,opt,name=offerer_address,json=offererAddress"`
	xxx_hidden_SellerAddress  *Address               `protobuf:"bytes,2,opt,name=seller_address,json=sellerAddress"`
	xxx_hidden_MintHash       *Hash                  `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash"`
	xxx_hidden_Quantity       int32                  `protobuf:"varint,4,opt,name=quantity"`
	xxx_hidden_Price          int32                  `protobuf:"varint,5,opt,name=price"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CreateBuyOfferRequestPayload) Reset() {
	*x = CreateBuyOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferRequestPayload) ProtoMessage() {}

func (x *CreateBuyOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBuyOfferRequestPayload) GetOffererAddress() *Address {
	if x != nil {
		return x.xxx_hidden_OffererAddress
	}
	return nil
}

func (x *CreateBuyOfferRequestPayload) GetSellerAddress() *Address {
	if x != nil {
		return x.xxx_hidden_SellerAddress
	}
	return nil
}

func (x *CreateBuyOfferRequestPayload) GetMintHash() *Hash {
	if x != nil {
		return x.xxx_hidden_MintHash
	}
	return nil
}

func (x *CreateBuyOfferRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.xxx_hidden_Quantity
	}
	return 0
}

func (x *CreateBuyOfferRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.xxx_hidden_Price
	}
	return 0
}

func (x *CreateBuyOfferRequestPayload) SetOffererAddress(v *Address) {
	x.xxx_hidden_OffererAddress = v
}

func (x *CreateBuyOfferRequestPayload) SetSellerAddress(v *Address) {
	x.xxx_hidden_SellerAddress = v
}

func (x *CreateBuyOfferRequestPayload) SetMintHash(v *Hash) {
	x.xxx_hidden_MintHash = v
}

func (x *CreateBuyOfferRequestPayload) SetQuantity(v int32) {
	x.xxx_hidden_Quantity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CreateBuyOfferRequestPayload) SetPrice(v int32) {
	x.xxx_hidden_Price = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CreateBuyOfferRequestPayload) HasOffererAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OffererAddress != nil
}

func (x *CreateBuyOfferRequestPayload) HasSellerAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SellerAddress != nil
}

func (x *CreateBuyOfferRequestPayload) HasMintHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MintHash != nil
}

func (x *CreateBuyOfferRequestPayload) HasQuantity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateBuyOfferRequestPayload) HasPrice() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateBuyOfferRequestPayload) ClearOffererAddress() {
	x.xxx_hidden_OffererAddress = nil
}

func (x *CreateBuyOfferRequestPayload) ClearSellerAddress() {
	x.xxx_hidden_SellerAddress = nil
}

func (x *CreateBuyOfferRequestPayload) ClearMintHash() {
	x.xxx_hidden_MintHash = nil
}

func (x *CreateBuyOfferRequestPayload) ClearQuantity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Quantity = 0
}

func (x *CreateBuyOfferRequestPayload) ClearPrice() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Price = 0
}

type CreateBuyOfferRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OffererAddress *Address
	SellerAddress  *Address
	MintHash       *Hash
	Quantity       *int32
	Price          *int32
}

func (b0 CreateBuyOfferRequestPayload_builder) Build() *CreateBuyOfferRequestPayload {
	m0 := &CreateBuyOfferRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OffererAddress = b.OffererAddress
	x.xxx_hidden_SellerAddress = b.SellerAddress
	x.xxx_hidden_MintHash = b.MintHash
	if b.Quantity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Quantity = *b.Quantity
	}
	if b.Price != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Price = *b.Price
	}
	return m0
}

type DeleteSellOfferRequest struct {
	state                  protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Payload     *DeleteSellOfferRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	xxx_hidden_PublicKey   *string                        `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                        `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSellOfferRequest) Reset() {
	*x = DeleteSellOfferRequest{}
	mi := &file_offers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferRequest) ProtoMessage() {}

func (x *DeleteSellOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSellOfferRequest) GetPayload() *DeleteSellOfferRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *DeleteSellOfferRequest) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *DeleteSellOfferRequest) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *DeleteSellOfferRequest) SetPayload(v *DeleteSellOfferRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *DeleteSellOfferRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DeleteSellOfferRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DeleteSellOfferRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *DeleteSellOfferRequest) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteSellOfferRequest) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeleteSellOfferRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *DeleteSellOfferRequest) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *DeleteSellOfferRequest) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type DeleteSellOfferRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *DeleteSellOfferRequestPayload
	PublicKey *string
	Signature *string
}

func (b0 DeleteSellOfferRequest_builder) Build() *DeleteSellOfferRequest {
	m0 := &DeleteSellOfferRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type DeleteSellOfferResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *string                `protobuf:"bytes,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSellOfferResponse) Reset() {
	*x = DeleteSellOfferResponse{}
	mi := &file_offers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferResponse) ProtoMessage() {}

func (x *DeleteSellOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSellOfferResponse) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *DeleteSellOfferResponse) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteSellOfferResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteSellOfferResponse) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

type DeleteSellOfferResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *string
}

func (b0 DeleteSellOfferResponse_builder) Build() *DeleteSellOfferResponse {
	m0 := &DeleteSellOfferResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type DeleteSellOfferRequestPayload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OfferHash *Hash                  `protobuf:"bytes,1,opt,name=offer_hash,json=offerHash"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteSellOfferRequestPayload) Reset() {
	*x = DeleteSellOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferRequestPayload) ProtoMessage() {}

func (x *DeleteSellOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSellOfferRequestPayload) GetOfferHash() *Hash {
	if x != nil {
		return x.xxx_hidden_OfferHash
	}
	return nil
}

func (x *DeleteSellOfferRequestPayload) SetOfferHash(v *Hash) {
	x.xxx_hidden_OfferHash = v
}

func (x *DeleteSellOfferRequestPayload) HasOfferHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OfferHash != nil
}

func (x *DeleteSellOfferRequestPayload) ClearOfferHash() {
	x.xxx_hidden_OfferHash = nil
}

type DeleteSellOfferRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OfferHash *Hash
}

func (b0 DeleteSellOfferRequestPayload_builder) Build() *DeleteSellOfferRequestPayload {
	m0 := &DeleteSellOfferRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OfferHash = b.OfferHash
	return m0
}

type DeleteBuyOfferRequest struct {
	state                  protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Payload     *DeleteBuyOfferRequestPayload `protobuf:"bytes,1,opt,name=payload"`
	xxx_hidden_PublicKey   *string                       `protobuf:"bytes,2,opt,name=public_key,json=publicKey"`
	xxx_hidden_Signature   *string                       `protobuf:"bytes,3,opt,name=signature"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteBuyOfferRequest) Reset() {
	*x = DeleteBuyOfferRequest{}
	mi := &file_offers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferRequest) ProtoMessage() {}

func (x *DeleteBuyOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBuyOfferRequest) GetPayload() *DeleteBuyOfferRequestPayload {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *DeleteBuyOfferRequest) GetPublicKey() string {
	if x != nil {
		if x.xxx_hidden_PublicKey != nil {
			return *x.xxx_hidden_PublicKey
		}
		return ""
	}
	return ""
}

func (x *DeleteBuyOfferRequest) GetSignature() string {
	if x != nil {
		if x.xxx_hidden_Signature != nil {
			return *x.xxx_hidden_Signature
		}
		return ""
	}
	return ""
}

func (x *DeleteBuyOfferRequest) SetPayload(v *DeleteBuyOfferRequestPayload) {
	x.xxx_hidden_Payload = v
}

func (x *DeleteBuyOfferRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *DeleteBuyOfferRequest) SetSignature(v string) {
	x.xxx_hidden_Signature = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *DeleteBuyOfferRequest) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *DeleteBuyOfferRequest) HasPublicKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteBuyOfferRequest) HasSignature() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeleteBuyOfferRequest) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *DeleteBuyOfferRequest) ClearPublicKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PublicKey = nil
}

func (x *DeleteBuyOfferRequest) ClearSignature() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Signature = nil
}

type DeleteBuyOfferRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payload   *DeleteBuyOfferRequestPayload
	PublicKey *string
	Signature *string
}

func (b0 DeleteBuyOfferRequest_builder) Build() *DeleteBuyOfferRequest {
	m0 := &DeleteBuyOfferRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payload = b.Payload
	if b.PublicKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PublicKey = b.PublicKey
	}
	if b.Signature != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Signature = b.Signature
	}
	return m0
}

type DeleteBuyOfferResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value       *string                `protobuf:"bytes,1,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteBuyOfferResponse) Reset() {
	*x = DeleteBuyOfferResponse{}
	mi := &file_offers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferResponse) ProtoMessage() {}

func (x *DeleteBuyOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBuyOfferResponse) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *DeleteBuyOfferResponse) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteBuyOfferResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteBuyOfferResponse) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Value = nil
}

type DeleteBuyOfferResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *string
}

func (b0 DeleteBuyOfferResponse_builder) Build() *DeleteBuyOfferResponse {
	m0 := &DeleteBuyOfferResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type DeleteBuyOfferRequestPayload struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OfferHash *Hash                  `protobuf:"bytes,1,opt,name=offer_hash,json=offerHash"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteBuyOfferRequestPayload) Reset() {
	*x = DeleteBuyOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferRequestPayload) ProtoMessage() {}

func (x *DeleteBuyOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBuyOfferRequestPayload) GetOfferHash() *Hash {
	if x != nil {
		return x.xxx_hidden_OfferHash
	}
	return nil
}

func (x *DeleteBuyOfferRequestPayload) SetOfferHash(v *Hash) {
	x.xxx_hidden_OfferHash = v
}

func (x *DeleteBuyOfferRequestPayload) HasOfferHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OfferHash != nil
}

func (x *DeleteBuyOfferRequestPayload) ClearOfferHash() {
	x.xxx_hidden_OfferHash = nil
}

type DeleteBuyOfferRequestPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OfferHash *Hash
}

func (b0 DeleteBuyOfferRequestPayload_builder) Build() *DeleteBuyOfferRequestPayload {
	m0 := &DeleteBuyOfferRequestPayload{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OfferHash = b.OfferHash
	return m0
}

var File_offers_proto protoreflect.FileDescriptor

const file_offers_proto_rawDesc = "" +
	"\n" +
	"\foffers.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\x1a\vtypes.proto\"Y\n" +
	"\x17CreateSellOfferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04hash\x18\x02 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hash\"X\n" +
	"\x16CreateBuyOfferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04hash\x18\x02 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\x04hash\"\xfb\x01\n" +
	"\x14GetSellOffersRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\x12F\n" +
	"\x0fofferer_address\x18\x04 \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\x0eoffererAddress\"\xf8\x01\n" +
	"\x13GetBuyOffersRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x127\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\bmintHash\x12D\n" +
	"\x0eseller_address\x18\x04 \x01(\v2\x1d.fractalengine.rpc.v1.AddressR\rsellerAddress\"\x98\x01\n" +
	"\x15GetSellOffersResponse\x12?\n" +
	"\x06offers\x18\x01 \x03(\v2'.fractalengine.rpc.v1.SellOfferWithMintR\x06offers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x96\x01\n" +
	"\x14GetBuyOffersResponse\x12>\n" +
	"\x06offers\x18\x01 \x03(\v2&.fractalengine.rpc.v1.BuyOfferWithMintR\x06offers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xb6\x01\n" +
	"\x16CreateSellOfferRequest\x12M\n" +
	"\apayload\x18\x01 \x01(\v23.fractalengine.rpc.v1.CreateSellOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\xf6\x01\n" +
	"\x1dCreateSellOfferRequestPayload\x12O\n" +
	"\x0fofferer_address\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\x0eoffererAddress\x12@\n" +
	"\tmint_hash\x18\x02 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\bmintHash\x12#\n" +
	"\bquantity\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\"\xb4\x01\n" +
	"\x15CreateBuyOfferRequest\x12L\n" +
	"\apayload\x18\x01 \x01(\v22.fractalengine.rpc.v1.CreateBuyOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\xc4\x02\n" +
	"\x1cCreateBuyOfferRequestPayload\x12O\n" +
	"\x0fofferer_address\x18\x01 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\x0eoffererAddress\x12M\n" +
	"\x0eseller_address\x18\x02 \x01(\v2\x1d.fractalengine.rpc.v1.AddressB\a\xbaH\x04r\x02\x10\x01R\rsellerAddress\x12@\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\bmintHash\x12#\n" +
	"\bquantity\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\"\xb6\x01\n" +
	"\x16DeleteSellOfferRequest\x12M\n" +
	"\apayload\x18\x01 \x01(\v23.fractalengine.rpc.v1.DeleteSellOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"/\n" +
	"\x17DeleteSellOfferResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"c\n" +
	"\x1dDeleteSellOfferRequestPayload\x12B\n" +
	"\n" +
	"offer_hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\tofferHash\"\xb4\x01\n" +
	"\x15DeleteBuyOfferRequest\x12L\n" +
	"\apayload\x18\x01 \x01(\v22.fractalengine.rpc.v1.DeleteBuyOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\".\n" +
	"\x16DeleteBuyOfferResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"b\n" +
	"\x1cDeleteBuyOfferRequestPayload\x12B\n" +
	"\n" +
	"offer_hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashB\a\xbaH\x04r\x02\x10\x01R\tofferHashB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\beditionsp\xe8\a"

var file_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_offers_proto_goTypes = []any{
	(*CreateSellOfferResponse)(nil),       // 0: fractalengine.rpc.v1.CreateSellOfferResponse
	(*CreateBuyOfferResponse)(nil),        // 1: fractalengine.rpc.v1.CreateBuyOfferResponse
	(*GetSellOffersRequest)(nil),          // 2: fractalengine.rpc.v1.GetSellOffersRequest
	(*GetBuyOffersRequest)(nil),           // 3: fractalengine.rpc.v1.GetBuyOffersRequest
	(*GetSellOffersResponse)(nil),         // 4: fractalengine.rpc.v1.GetSellOffersResponse
	(*GetBuyOffersResponse)(nil),          // 5: fractalengine.rpc.v1.GetBuyOffersResponse
	(*CreateSellOfferRequest)(nil),        // 6: fractalengine.rpc.v1.CreateSellOfferRequest
	(*CreateSellOfferRequestPayload)(nil), // 7: fractalengine.rpc.v1.CreateSellOfferRequestPayload
	(*CreateBuyOfferRequest)(nil),         // 8: fractalengine.rpc.v1.CreateBuyOfferRequest
	(*CreateBuyOfferRequestPayload)(nil),  // 9: fractalengine.rpc.v1.CreateBuyOfferRequestPayload
	(*DeleteSellOfferRequest)(nil),        // 10: fractalengine.rpc.v1.DeleteSellOfferRequest
	(*DeleteSellOfferResponse)(nil),       // 11: fractalengine.rpc.v1.DeleteSellOfferResponse
	(*DeleteSellOfferRequestPayload)(nil), // 12: fractalengine.rpc.v1.DeleteSellOfferRequestPayload
	(*DeleteBuyOfferRequest)(nil),         // 13: fractalengine.rpc.v1.DeleteBuyOfferRequest
	(*DeleteBuyOfferResponse)(nil),        // 14: fractalengine.rpc.v1.DeleteBuyOfferResponse
	(*DeleteBuyOfferRequestPayload)(nil),  // 15: fractalengine.rpc.v1.DeleteBuyOfferRequestPayload
	(*Hash)(nil),                          // 16: fractalengine.rpc.v1.Hash
	(*wrapperspb.Int32Value)(nil),         // 17: google.protobuf.Int32Value
	(*Address)(nil),                       // 18: fractalengine.rpc.v1.Address
	(*SellOfferWithMint)(nil),             // 19: fractalengine.rpc.v1.SellOfferWithMint
	(*BuyOfferWithMint)(nil),              // 20: fractalengine.rpc.v1.BuyOfferWithMint
}
var file_offers_proto_depIdxs = []int32{
	16, // 0: fractalengine.rpc.v1.CreateSellOfferResponse.hash:type_name -> fractalengine.rpc.v1.Hash
	16, // 1: fractalengine.rpc.v1.CreateBuyOfferResponse.hash:type_name -> fractalengine.rpc.v1.Hash
	17, // 2: fractalengine.rpc.v1.GetSellOffersRequest.limit:type_name -> google.protobuf.Int32Value
	17, // 3: fractalengine.rpc.v1.GetSellOffersRequest.page:type_name -> google.protobuf.Int32Value
	16, // 4: fractalengine.rpc.v1.GetSellOffersRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	18, // 5: fractalengine.rpc.v1.GetSellOffersRequest.offerer_address:type_name -> fractalengine.rpc.v1.Address
	17, // 6: fractalengine.rpc.v1.GetBuyOffersRequest.limit:type_name -> google.protobuf.Int32Value
	17, // 7: fractalengine.rpc.v1.GetBuyOffersRequest.page:type_name -> google.protobuf.Int32Value
	16, // 8: fractalengine.rpc.v1.GetBuyOffersRequest.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	18, // 9: fractalengine.rpc.v1.GetBuyOffersRequest.seller_address:type_name -> fractalengine.rpc.v1.Address
	19, // 10: fractalengine.rpc.v1.GetSellOffersResponse.offers:type_name -> fractalengine.rpc.v1.SellOfferWithMint
	20, // 11: fractalengine.rpc.v1.GetBuyOffersResponse.offers:type_name -> fractalengine.rpc.v1.BuyOfferWithMint
	7,  // 12: fractalengine.rpc.v1.CreateSellOfferRequest.payload:type_name -> fractalengine.rpc.v1.CreateSellOfferRequestPayload
	18, // 13: fractalengine.rpc.v1.CreateSellOfferRequestPayload.offerer_address:type_name -> fractalengine.rpc.v1.Address
	16, // 14: fractalengine.rpc.v1.CreateSellOfferRequestPayload.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	9,  // 15: fractalengine.rpc.v1.CreateBuyOfferRequest.payload:type_name -> fractalengine.rpc.v1.CreateBuyOfferRequestPayload
	18, // 16: fractalengine.rpc.v1.CreateBuyOfferRequestPayload.offerer_address:type_name -> fractalengine.rpc.v1.Address
	18, // 17: fractalengine.rpc.v1.CreateBuyOfferRequestPayload.seller_address:type_name -> fractalengine.rpc.v1.Address
	16, // 18: fractalengine.rpc.v1.CreateBuyOfferRequestPayload.mint_hash:type_name -> fractalengine.rpc.v1.Hash
	12, // 19: fractalengine.rpc.v1.DeleteSellOfferRequest.payload:type_name -> fractalengine.rpc.v1.DeleteSellOfferRequestPayload
	16, // 20: fractalengine.rpc.v1.DeleteSellOfferRequestPayload.offer_hash:type_name -> fractalengine.rpc.v1.Hash
	15, // 21: fractalengine.rpc.v1.DeleteBuyOfferRequest.payload:type_name -> fractalengine.rpc.v1.DeleteBuyOfferRequestPayload
	16, // 22: fractalengine.rpc.v1.DeleteBuyOfferRequestPayload.offer_hash:type_name -> fractalengine.rpc.v1.Hash
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_offers_proto_init() }
func file_offers_proto_init() {
	if File_offers_proto != nil {
		return
	}
	file_common_proto_init()
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offers_proto_rawDesc), len(file_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offers_proto_goTypes,
		DependencyIndexes: file_offers_proto_depIdxs,
		MessageInfos:      file_offers_proto_msgTypes,
	}.Build()
	File_offers_proto = out.File
	file_offers_proto_goTypes = nil
	file_offers_proto_depIdxs = nil
}
