// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: offers.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSellOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellOfferResponse) Reset() {
	*x = CreateSellOfferResponse{}
	mi := &file_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferResponse) ProtoMessage() {}

func (x *CreateSellOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateSellOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSellOfferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSellOfferResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CreateBuyOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuyOfferResponse) Reset() {
	*x = CreateBuyOfferResponse{}
	mi := &file_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferResponse) ProtoMessage() {}

func (x *CreateBuyOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuyOfferResponse.ProtoReflect.Descriptor instead.
func (*CreateBuyOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBuyOfferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBuyOfferResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetSellOffersRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Limit          *wrapperspb.Int32Value  `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page           *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	MintHash       *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	OffererAddress *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSellOffersRequest) Reset() {
	*x = GetSellOffersRequest{}
	mi := &file_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellOffersRequest) ProtoMessage() {}

func (x *GetSellOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellOffersRequest.ProtoReflect.Descriptor instead.
func (*GetSellOffersRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{2}
}

func (x *GetSellOffersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetSellOffersRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetSellOffersRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.MintHash
	}
	return nil
}

func (x *GetSellOffersRequest) GetOffererAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.OffererAddress
	}
	return nil
}

type GetBuyOffersRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Limit         *wrapperspb.Int32Value  `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	MintHash      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	SellerAddress *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuyOffersRequest) Reset() {
	*x = GetBuyOffersRequest{}
	mi := &file_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOffersRequest) ProtoMessage() {}

func (x *GetBuyOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyOffersRequest.ProtoReflect.Descriptor instead.
func (*GetBuyOffersRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{3}
}

func (x *GetBuyOffersRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetBuyOffersRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetBuyOffersRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.MintHash
	}
	return nil
}

func (x *GetBuyOffersRequest) GetSellerAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.SellerAddress
	}
	return nil
}

type GetSellOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*SellOfferWithMint   `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellOffersResponse) Reset() {
	*x = GetSellOffersResponse{}
	mi := &file_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellOffersResponse) ProtoMessage() {}

func (x *GetSellOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellOffersResponse.ProtoReflect.Descriptor instead.
func (*GetSellOffersResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{4}
}

func (x *GetSellOffersResponse) GetOffers() []*SellOfferWithMint {
	if x != nil {
		return x.Offers
	}
	return nil
}

func (x *GetSellOffersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSellOffersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSellOffersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBuyOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*BuyOfferWithMint    `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuyOffersResponse) Reset() {
	*x = GetBuyOffersResponse{}
	mi := &file_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuyOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuyOffersResponse) ProtoMessage() {}

func (x *GetBuyOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuyOffersResponse.ProtoReflect.Descriptor instead.
func (*GetBuyOffersResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{5}
}

func (x *GetBuyOffersResponse) GetOffers() []*BuyOfferWithMint {
	if x != nil {
		return x.Offers
	}
	return nil
}

func (x *GetBuyOffersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBuyOffersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBuyOffersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateSellOfferRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payload       *CreateSellOfferRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                         `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSellOfferRequest) Reset() {
	*x = CreateSellOfferRequest{}
	mi := &file_offers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferRequest) ProtoMessage() {}

func (x *CreateSellOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateSellOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSellOfferRequest) GetPayload() *CreateSellOfferRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateSellOfferRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateSellOfferRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateSellOfferRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OffererAddress string                 `protobuf:"bytes,1,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	MintHash       string                 `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSellOfferRequestPayload) Reset() {
	*x = CreateSellOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSellOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellOfferRequestPayload) ProtoMessage() {}

func (x *CreateSellOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellOfferRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateSellOfferRequestPayload) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSellOfferRequestPayload) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *CreateSellOfferRequestPayload) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *CreateSellOfferRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateSellOfferRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateBuyOfferRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Payload       *CreateBuyOfferRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                        `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuyOfferRequest) Reset() {
	*x = CreateBuyOfferRequest{}
	mi := &file_offers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferRequest) ProtoMessage() {}

func (x *CreateBuyOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuyOfferRequest.ProtoReflect.Descriptor instead.
func (*CreateBuyOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBuyOfferRequest) GetPayload() *CreateBuyOfferRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateBuyOfferRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateBuyOfferRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateBuyOfferRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OffererAddress string                 `protobuf:"bytes,1,opt,name=offerer_address,json=offererAddress,proto3" json:"offerer_address,omitempty"`
	SellerAddress  string                 `protobuf:"bytes,2,opt,name=seller_address,json=sellerAddress,proto3" json:"seller_address,omitempty"`
	MintHash       string                 `protobuf:"bytes,3,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBuyOfferRequestPayload) Reset() {
	*x = CreateBuyOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuyOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuyOfferRequestPayload) ProtoMessage() {}

func (x *CreateBuyOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuyOfferRequestPayload.ProtoReflect.Descriptor instead.
func (*CreateBuyOfferRequestPayload) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBuyOfferRequestPayload) GetOffererAddress() string {
	if x != nil {
		return x.OffererAddress
	}
	return ""
}

func (x *CreateBuyOfferRequestPayload) GetSellerAddress() string {
	if x != nil {
		return x.SellerAddress
	}
	return ""
}

func (x *CreateBuyOfferRequestPayload) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *CreateBuyOfferRequestPayload) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateBuyOfferRequestPayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteSellOfferRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payload       *DeleteSellOfferRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                         `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferRequest) Reset() {
	*x = DeleteSellOfferRequest{}
	mi := &file_offers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferRequest) ProtoMessage() {}

func (x *DeleteSellOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferRequest.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSellOfferRequest) GetPayload() *DeleteSellOfferRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeleteSellOfferRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeleteSellOfferRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type DeleteSellOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferResponse) Reset() {
	*x = DeleteSellOfferResponse{}
	mi := &file_offers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferResponse) ProtoMessage() {}

func (x *DeleteSellOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferResponse.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSellOfferResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteSellOfferRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferHash     string                 `protobuf:"bytes,1,opt,name=offer_hash,json=offerHash,proto3" json:"offer_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSellOfferRequestPayload) Reset() {
	*x = DeleteSellOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSellOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellOfferRequestPayload) ProtoMessage() {}

func (x *DeleteSellOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellOfferRequestPayload.ProtoReflect.Descriptor instead.
func (*DeleteSellOfferRequestPayload) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSellOfferRequestPayload) GetOfferHash() string {
	if x != nil {
		return x.OfferHash
	}
	return ""
}

type DeleteBuyOfferRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Payload       *DeleteBuyOfferRequestPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                        `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuyOfferRequest) Reset() {
	*x = DeleteBuyOfferRequest{}
	mi := &file_offers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferRequest) ProtoMessage() {}

func (x *DeleteBuyOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuyOfferRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuyOfferRequest) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBuyOfferRequest) GetPayload() *DeleteBuyOfferRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeleteBuyOfferRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DeleteBuyOfferRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type DeleteBuyOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuyOfferResponse) Reset() {
	*x = DeleteBuyOfferResponse{}
	mi := &file_offers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferResponse) ProtoMessage() {}

func (x *DeleteBuyOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuyOfferResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuyOfferResponse) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBuyOfferResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteBuyOfferRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferHash     string                 `protobuf:"bytes,1,opt,name=offer_hash,json=offerHash,proto3" json:"offer_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuyOfferRequestPayload) Reset() {
	*x = DeleteBuyOfferRequestPayload{}
	mi := &file_offers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuyOfferRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuyOfferRequestPayload) ProtoMessage() {}

func (x *DeleteBuyOfferRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_offers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuyOfferRequestPayload.ProtoReflect.Descriptor instead.
func (*DeleteBuyOfferRequestPayload) Descriptor() ([]byte, []int) {
	return file_offers_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteBuyOfferRequestPayload) GetOfferHash() string {
	if x != nil {
		return x.OfferHash
	}
	return ""
}

var File_offers_proto protoreflect.FileDescriptor

const file_offers_proto_rawDesc = "" +
	"\n" +
	"\foffers.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\"W\n" +
	"\x17CreateSellOfferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04hash\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\x04hash\"V\n" +
	"\x16CreateBuyOfferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04hash\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\x04hash\"\xc7\x02\n" +
	"\x14GetSellOffersRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x12S\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\x12v\n" +
	"\x0fofferer_address\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\x0eoffererAddress\"\xc4\x02\n" +
	"\x13GetBuyOffersRequest\x121\n" +
	"\x05limit\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\x12S\n" +
	"\tmint_hash\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\x12t\n" +
	"\x0eseller_address\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\rsellerAddress\"\x98\x01\n" +
	"\x15GetSellOffersResponse\x12?\n" +
	"\x06offers\x18\x01 \x03(\v2'.fractalengine.rpc.v1.SellOfferWithMintR\x06offers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x96\x01\n" +
	"\x14GetBuyOffersResponse\x12>\n" +
	"\x06offers\x18\x01 \x03(\v2&.fractalengine.rpc.v1.BuyOfferWithMintR\x06offers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xb6\x01\n" +
	"\x16CreateSellOfferRequest\x12M\n" +
	"\apayload\x18\x01 \x01(\v23.fractalengine.rpc.v1.CreateSellOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\xf8\x01\n" +
	"\x1dCreateSellOfferRequestPayload\x12Z\n" +
	"\x0fofferer_address\x18\x01 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\x0eoffererAddress\x127\n" +
	"\tmint_hash\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\bmintHash\x12#\n" +
	"\bquantity\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\"\xb4\x01\n" +
	"\x15CreateBuyOfferRequest\x12L\n" +
	"\apayload\x18\x01 \x01(\v22.fractalengine.rpc.v1.CreateBuyOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"\xd1\x02\n" +
	"\x1cCreateBuyOfferRequestPayload\x12Z\n" +
	"\x0fofferer_address\x18\x01 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\x0eoffererAddress\x12X\n" +
	"\x0eseller_address\x18\x02 \x01(\tB1\xbaH.r,\x10\x012(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\rsellerAddress\x127\n" +
	"\tmint_hash\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\bmintHash\x12#\n" +
	"\bquantity\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\bquantity\x12\x1d\n" +
	"\x05price\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x05price\"\xb6\x01\n" +
	"\x16DeleteSellOfferRequest\x12M\n" +
	"\apayload\x18\x01 \x01(\v23.fractalengine.rpc.v1.DeleteSellOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\"/\n" +
	"\x17DeleteSellOfferResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"Z\n" +
	"\x1dDeleteSellOfferRequestPayload\x129\n" +
	"\n" +
	"offer_hash\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\tofferHash\"\xb4\x01\n" +
	"\x15DeleteBuyOfferRequest\x12L\n" +
	"\apayload\x18\x01 \x01(\v22.fractalengine.rpc.v1.DeleteBuyOfferRequestPayloadR\apayload\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12%\n" +
	"\tsignature\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tsignature\".\n" +
	"\x16DeleteBuyOfferResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"Y\n" +
	"\x1cDeleteBuyOfferRequestPayload\x129\n" +
	"\n" +
	"offer_hash\x18\x01 \x01(\tB\x1a\xbaH\x17r\x15\x10\x012\x11^[a-fA-F0-9]{64}$R\tofferHashB\x12Z\x10pkg/rpc/protocolb\x06proto3"

var (
	file_offers_proto_rawDescOnce sync.Once
	file_offers_proto_rawDescData []byte
)

func file_offers_proto_rawDescGZIP() []byte {
	file_offers_proto_rawDescOnce.Do(func() {
		file_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offers_proto_rawDesc), len(file_offers_proto_rawDesc)))
	})
	return file_offers_proto_rawDescData
}

var file_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_offers_proto_goTypes = []any{
	(*CreateSellOfferResponse)(nil),       // 0: fractalengine.rpc.v1.CreateSellOfferResponse
	(*CreateBuyOfferResponse)(nil),        // 1: fractalengine.rpc.v1.CreateBuyOfferResponse
	(*GetSellOffersRequest)(nil),          // 2: fractalengine.rpc.v1.GetSellOffersRequest
	(*GetBuyOffersRequest)(nil),           // 3: fractalengine.rpc.v1.GetBuyOffersRequest
	(*GetSellOffersResponse)(nil),         // 4: fractalengine.rpc.v1.GetSellOffersResponse
	(*GetBuyOffersResponse)(nil),          // 5: fractalengine.rpc.v1.GetBuyOffersResponse
	(*CreateSellOfferRequest)(nil),        // 6: fractalengine.rpc.v1.CreateSellOfferRequest
	(*CreateSellOfferRequestPayload)(nil), // 7: fractalengine.rpc.v1.CreateSellOfferRequestPayload
	(*CreateBuyOfferRequest)(nil),         // 8: fractalengine.rpc.v1.CreateBuyOfferRequest
	(*CreateBuyOfferRequestPayload)(nil),  // 9: fractalengine.rpc.v1.CreateBuyOfferRequestPayload
	(*DeleteSellOfferRequest)(nil),        // 10: fractalengine.rpc.v1.DeleteSellOfferRequest
	(*DeleteSellOfferResponse)(nil),       // 11: fractalengine.rpc.v1.DeleteSellOfferResponse
	(*DeleteSellOfferRequestPayload)(nil), // 12: fractalengine.rpc.v1.DeleteSellOfferRequestPayload
	(*DeleteBuyOfferRequest)(nil),         // 13: fractalengine.rpc.v1.DeleteBuyOfferRequest
	(*DeleteBuyOfferResponse)(nil),        // 14: fractalengine.rpc.v1.DeleteBuyOfferResponse
	(*DeleteBuyOfferRequestPayload)(nil),  // 15: fractalengine.rpc.v1.DeleteBuyOfferRequestPayload
	(*wrapperspb.Int32Value)(nil),         // 16: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),        // 17: google.protobuf.StringValue
	(*SellOfferWithMint)(nil),             // 18: fractalengine.rpc.v1.SellOfferWithMint
	(*BuyOfferWithMint)(nil),              // 19: fractalengine.rpc.v1.BuyOfferWithMint
}
var file_offers_proto_depIdxs = []int32{
	16, // 0: fractalengine.rpc.v1.GetSellOffersRequest.limit:type_name -> google.protobuf.Int32Value
	16, // 1: fractalengine.rpc.v1.GetSellOffersRequest.page:type_name -> google.protobuf.Int32Value
	17, // 2: fractalengine.rpc.v1.GetSellOffersRequest.mint_hash:type_name -> google.protobuf.StringValue
	17, // 3: fractalengine.rpc.v1.GetSellOffersRequest.offerer_address:type_name -> google.protobuf.StringValue
	16, // 4: fractalengine.rpc.v1.GetBuyOffersRequest.limit:type_name -> google.protobuf.Int32Value
	16, // 5: fractalengine.rpc.v1.GetBuyOffersRequest.page:type_name -> google.protobuf.Int32Value
	17, // 6: fractalengine.rpc.v1.GetBuyOffersRequest.mint_hash:type_name -> google.protobuf.StringValue
	17, // 7: fractalengine.rpc.v1.GetBuyOffersRequest.seller_address:type_name -> google.protobuf.StringValue
	18, // 8: fractalengine.rpc.v1.GetSellOffersResponse.offers:type_name -> fractalengine.rpc.v1.SellOfferWithMint
	19, // 9: fractalengine.rpc.v1.GetBuyOffersResponse.offers:type_name -> fractalengine.rpc.v1.BuyOfferWithMint
	7,  // 10: fractalengine.rpc.v1.CreateSellOfferRequest.payload:type_name -> fractalengine.rpc.v1.CreateSellOfferRequestPayload
	9,  // 11: fractalengine.rpc.v1.CreateBuyOfferRequest.payload:type_name -> fractalengine.rpc.v1.CreateBuyOfferRequestPayload
	12, // 12: fractalengine.rpc.v1.DeleteSellOfferRequest.payload:type_name -> fractalengine.rpc.v1.DeleteSellOfferRequestPayload
	15, // 13: fractalengine.rpc.v1.DeleteBuyOfferRequest.payload:type_name -> fractalengine.rpc.v1.DeleteBuyOfferRequestPayload
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_offers_proto_init() }
func file_offers_proto_init() {
	if File_offers_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offers_proto_rawDesc), len(file_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offers_proto_goTypes,
		DependencyIndexes: file_offers_proto_depIdxs,
		MessageInfos:      file_offers_proto_msgTypes,
	}.Build()
	File_offers_proto = out.File
	file_offers_proto_goTypes = nil
	file_offers_proto_depIdxs = nil
}
