// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payments.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewPaymentRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InvoiceHash *Hash                  `protobuf:"bytes,1,opt,name=invoice_hash,json=invoiceHash"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateNewPaymentRequest) Reset() {
	*x = CreateNewPaymentRequest{}
	mi := &file_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewPaymentRequest) ProtoMessage() {}

func (x *CreateNewPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateNewPaymentRequest) GetInvoiceHash() *Hash {
	if x != nil {
		return x.xxx_hidden_InvoiceHash
	}
	return nil
}

func (x *CreateNewPaymentRequest) SetInvoiceHash(v *Hash) {
	x.xxx_hidden_InvoiceHash = v
}

func (x *CreateNewPaymentRequest) HasInvoiceHash() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_InvoiceHash != nil
}

func (x *CreateNewPaymentRequest) ClearInvoiceHash() {
	x.xxx_hidden_InvoiceHash = nil
}

type CreateNewPaymentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InvoiceHash *Hash
}

func (b0 CreateNewPaymentRequest_builder) Build() *CreateNewPaymentRequest {
	m0 := &CreateNewPaymentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InvoiceHash = b.InvoiceHash
	return m0
}

type CreateNewPaymentResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values map[string]string      `protobuf:"bytes,1,rep,name=values" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateNewPaymentResponse) Reset() {
	*x = CreateNewPaymentResponse{}
	mi := &file_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewPaymentResponse) ProtoMessage() {}

func (x *CreateNewPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateNewPaymentResponse) GetValues() map[string]string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *CreateNewPaymentResponse) SetValues(v map[string]string) {
	x.xxx_hidden_Values = v
}

type CreateNewPaymentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values map[string]string
}

func (b0 CreateNewPaymentResponse_builder) Build() *CreateNewPaymentResponse {
	m0 := &CreateNewPaymentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

var File_payments_proto protoreflect.FileDescriptor

const file_payments_proto_rawDesc = "" +
	"\n" +
	"\x0epayments.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\vtypes.proto\"X\n" +
	"\x17CreateNewPaymentRequest\x12=\n" +
	"\finvoice_hash\x18\x01 \x01(\v2\x1a.fractalengine.rpc.v1.HashR\vinvoiceHash\"\xa9\x01\n" +
	"\x18CreateNewPaymentResponse\x12R\n" +
	"\x06values\x18\x01 \x03(\v2:.fractalengine.rpc.v1.CreateNewPaymentResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\beditionsp\xe8\a"

var file_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payments_proto_goTypes = []any{
	(*CreateNewPaymentRequest)(nil),  // 0: fractalengine.rpc.v1.CreateNewPaymentRequest
	(*CreateNewPaymentResponse)(nil), // 1: fractalengine.rpc.v1.CreateNewPaymentResponse
	nil,                              // 2: fractalengine.rpc.v1.CreateNewPaymentResponse.ValuesEntry
	(*Hash)(nil),                     // 3: fractalengine.rpc.v1.Hash
}
var file_payments_proto_depIdxs = []int32{
	3, // 0: fractalengine.rpc.v1.CreateNewPaymentRequest.invoice_hash:type_name -> fractalengine.rpc.v1.Hash
	2, // 1: fractalengine.rpc.v1.CreateNewPaymentResponse.values:type_name -> fractalengine.rpc.v1.CreateNewPaymentResponse.ValuesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payments_proto_init() }
func file_payments_proto_init() {
	if File_payments_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_proto_rawDesc), len(file_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payments_proto_goTypes,
		DependencyIndexes: file_payments_proto_depIdxs,
		MessageInfos:      file_payments_proto_msgTypes,
	}.Build()
	File_payments_proto = out.File
	file_payments_proto_goTypes = nil
	file_payments_proto_depIdxs = nil
}
