// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpc.proto

package protocol

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x14fractalengine.rpc.v1\x1a\n" +
	"doge.proto\x1a\fhealth.proto\x1a\x0einvoices.proto\x1a\vmints.proto\x1a\foffers.proto\x1a\x0epayments.proto\x1a\vstats.proto\x1a\ftokens.proto\x1a$gnostic/openapi/v3/annotations.proto2\xc3\x17\n" +
	"\x17FractalEngineRpcService\x12v\n" +
	"\vDogeConfirm\x12(.fractalengine.rpc.v1.DogeConfirmRequest\x1a).fractalengine.rpc.v1.DogeConfirmResponse\"\x12\xbaG\x0f\n" +
	"\x04Doge\x12\aConfirm\x12j\n" +
	"\bDogeSend\x12%.fractalengine.rpc.v1.DogeSendRequest\x1a&.fractalengine.rpc.v1.DogeSendResponse\"\x0f\xbaG\f\n" +
	"\x04Doge\x12\x04Send\x12o\n" +
	"\tDogeTopUp\x12&.fractalengine.rpc.v1.DogeTopUpRequest\x1a'.fractalengine.rpc.v1.DogeTopUpResponse\"\x11\xbaG\x0e\n" +
	"\x04Doge\x12\x06Top Up\x12u\n" +
	"\tGetHealth\x12&.fractalengine.rpc.v1.GetHealthRequest\x1a'.fractalengine.rpc.v1.GetHealthResponse\"\x17\xbaG\x14\n" +
	"\x06Health\x12\n" +
	"Get Health\x12p\n" +
	"\bGetStats\x12%.fractalengine.rpc.v1.GetStatsRequest\x1a&.fractalengine.rpc.v1.GetStatsResponse\"\x15\xbaG\x12\n" +
	"\x05Stats\x12\tGet Stats\x12\x7f\n" +
	"\vGetInvoices\x12(.fractalengine.rpc.v1.GetInvoicesRequest\x1a).fractalengine.rpc.v1.GetInvoicesResponse\"\x1b\xbaG\x18\n" +
	"\bInvoices\x12\fGet Invoices\x12\x8c\x01\n" +
	"\x0eGetAllInvoices\x12+.fractalengine.rpc.v1.GetAllInvoicesRequest\x1a,.fractalengine.rpc.v1.GetAllInvoicesResponse\"\x1f\xbaG\x1c\n" +
	"\bInvoices\x12\x10Get All Invoices\x12\x87\x01\n" +
	"\rCreateInvoice\x12*.fractalengine.rpc.v1.CreateInvoiceRequest\x1a+.fractalengine.rpc.v1.CreateInvoiceResponse\"\x1d\xbaG\x1a\n" +
	"\bInvoices\x12\x0eCreate Invoice\x12\xac\x01\n" +
	"\x16CreateInvoiceSignature\x123.fractalengine.rpc.v1.CreateInvoiceSignatureRequest\x1a4.fractalengine.rpc.v1.CreateInvoiceSignatureResponse\"'\xbaG$\n" +
	"\bInvoices\x12\x18Create Invoice Signature\x12p\n" +
	"\bGetMints\x12%.fractalengine.rpc.v1.GetMintsRequest\x1a&.fractalengine.rpc.v1.GetMintsResponse\"\x15\xbaG\x12\n" +
	"\x05Mints\x12\tGet Mints\x12l\n" +
	"\aGetMint\x12$.fractalengine.rpc.v1.GetMintRequest\x1a%.fractalengine.rpc.v1.GetMintResponse\"\x14\xbaG\x11\n" +
	"\x05Mints\x12\bGet Mint\x12x\n" +
	"\n" +
	"CreateMint\x12'.fractalengine.rpc.v1.CreateMintRequest\x1a(.fractalengine.rpc.v1.CreateMintResponse\"\x17\xbaG\x14\n" +
	"\x05Mints\x12\vCreate Mint\x12x\n" +
	"\n" +
	"ExpandMint\x12'.fractalengine.rpc.v1.ExpandMintRequest\x1a(.fractalengine.rpc.v1.ExpandMintResponse\"\x17\xbaG\x14\n" +
	"\x05Mints\x12\vExpand Mint\x12\x90\x01\n" +
	"\x10CreateNewPayment\x12-.fractalengine.rpc.v1.CreateNewPaymentRequest\x1a..fractalengine.rpc.v1.CreateNewPaymentResponse\"\x1d\xbaG\x1a\n" +
	"\bPayments\x12\x0eCreate Payment\x12\xb7\x01\n" +
	"\x17GetPendingTokenBalances\x124.fractalengine.rpc.v1.GetPendingTokenBalancesRequest\x1a5.fractalengine.rpc.v1.GetPendingTokenBalancesResponse\"/\xbaG,\n" +
	"\x0eToken Balances\x12\x1aGet Pending Token Balances\x12\x9a\x01\n" +
	"\x10GetTokenBalances\x12-.fractalengine.rpc.v1.GetTokenBalancesRequest\x1a..fractalengine.rpc.v1.GetTokenBalancesResponse\"'\xbaG$\n" +
	"\x0eToken Balances\x12\x12Get Token Balances\x12\x8b\x01\n" +
	"\rGetSellOffers\x12*.fractalengine.rpc.v1.GetSellOffersRequest\x1a+.fractalengine.rpc.v1.GetSellOffersResponse\"!\xbaG\x1e\n" +
	"\vSell Offers\x12\x0fGet Sell Offers\x12\x93\x01\n" +
	"\x0fCreateSellOffer\x12,.fractalengine.rpc.v1.CreateSellOfferRequest\x1a-.fractalengine.rpc.v1.CreateSellOfferResponse\"#\xbaG \n" +
	"\vSell Offers\x12\x11Create Sell Offer\x12\x93\x01\n" +
	"\x0fDeleteSellOffer\x12,.fractalengine.rpc.v1.DeleteSellOfferRequest\x1a-.fractalengine.rpc.v1.DeleteSellOfferResponse\"#\xbaG \n" +
	"\vSell Offers\x12\x11Delete Sell Offer\x12\x86\x01\n" +
	"\fGetBuyOffers\x12).fractalengine.rpc.v1.GetBuyOffersRequest\x1a*.fractalengine.rpc.v1.GetBuyOffersResponse\"\x1f\xbaG\x1c\n" +
	"\n" +
	"Buy Offers\x12\x0eGet Buy Offers\x12\x8e\x01\n" +
	"\x0eCreateBuyOffer\x12+.fractalengine.rpc.v1.CreateBuyOfferRequest\x1a,.fractalengine.rpc.v1.CreateBuyOfferResponse\"!\xbaG\x1e\n" +
	"\n" +
	"Buy Offers\x12\x10Create Buy Offer\x12\x8e\x01\n" +
	"\x0eDeleteBuyOffer\x12+.fractalengine.rpc.v1.DeleteBuyOfferRequest\x1a,.fractalengine.rpc.v1.DeleteBuyOfferResponse\"!\xbaG\x1e\n" +
	"\n" +
	"Buy Offers\x12\x10Delete Buy OfferB.Z,dogecoin.org/fractal-engine/pkg/rpc/protocolb\beditionsp\xe8\a"

var file_rpc_proto_goTypes = []any{
	(*DogeConfirmRequest)(nil),              // 0: fractalengine.rpc.v1.DogeConfirmRequest
	(*DogeSendRequest)(nil),                 // 1: fractalengine.rpc.v1.DogeSendRequest
	(*DogeTopUpRequest)(nil),                // 2: fractalengine.rpc.v1.DogeTopUpRequest
	(*GetHealthRequest)(nil),                // 3: fractalengine.rpc.v1.GetHealthRequest
	(*GetStatsRequest)(nil),                 // 4: fractalengine.rpc.v1.GetStatsRequest
	(*GetInvoicesRequest)(nil),              // 5: fractalengine.rpc.v1.GetInvoicesRequest
	(*GetAllInvoicesRequest)(nil),           // 6: fractalengine.rpc.v1.GetAllInvoicesRequest
	(*CreateInvoiceRequest)(nil),            // 7: fractalengine.rpc.v1.CreateInvoiceRequest
	(*CreateInvoiceSignatureRequest)(nil),   // 8: fractalengine.rpc.v1.CreateInvoiceSignatureRequest
	(*GetMintsRequest)(nil),                 // 9: fractalengine.rpc.v1.GetMintsRequest
	(*GetMintRequest)(nil),                  // 10: fractalengine.rpc.v1.GetMintRequest
	(*CreateMintRequest)(nil),               // 11: fractalengine.rpc.v1.CreateMintRequest
	(*ExpandMintRequest)(nil),               // 12: fractalengine.rpc.v1.ExpandMintRequest
	(*CreateNewPaymentRequest)(nil),         // 13: fractalengine.rpc.v1.CreateNewPaymentRequest
	(*GetPendingTokenBalancesRequest)(nil),  // 14: fractalengine.rpc.v1.GetPendingTokenBalancesRequest
	(*GetTokenBalancesRequest)(nil),         // 15: fractalengine.rpc.v1.GetTokenBalancesRequest
	(*GetSellOffersRequest)(nil),            // 16: fractalengine.rpc.v1.GetSellOffersRequest
	(*CreateSellOfferRequest)(nil),          // 17: fractalengine.rpc.v1.CreateSellOfferRequest
	(*DeleteSellOfferRequest)(nil),          // 18: fractalengine.rpc.v1.DeleteSellOfferRequest
	(*GetBuyOffersRequest)(nil),             // 19: fractalengine.rpc.v1.GetBuyOffersRequest
	(*CreateBuyOfferRequest)(nil),           // 20: fractalengine.rpc.v1.CreateBuyOfferRequest
	(*DeleteBuyOfferRequest)(nil),           // 21: fractalengine.rpc.v1.DeleteBuyOfferRequest
	(*DogeConfirmResponse)(nil),             // 22: fractalengine.rpc.v1.DogeConfirmResponse
	(*DogeSendResponse)(nil),                // 23: fractalengine.rpc.v1.DogeSendResponse
	(*DogeTopUpResponse)(nil),               // 24: fractalengine.rpc.v1.DogeTopUpResponse
	(*GetHealthResponse)(nil),               // 25: fractalengine.rpc.v1.GetHealthResponse
	(*GetStatsResponse)(nil),                // 26: fractalengine.rpc.v1.GetStatsResponse
	(*GetInvoicesResponse)(nil),             // 27: fractalengine.rpc.v1.GetInvoicesResponse
	(*GetAllInvoicesResponse)(nil),          // 28: fractalengine.rpc.v1.GetAllInvoicesResponse
	(*CreateInvoiceResponse)(nil),           // 29: fractalengine.rpc.v1.CreateInvoiceResponse
	(*CreateInvoiceSignatureResponse)(nil),  // 30: fractalengine.rpc.v1.CreateInvoiceSignatureResponse
	(*GetMintsResponse)(nil),                // 31: fractalengine.rpc.v1.GetMintsResponse
	(*GetMintResponse)(nil),                 // 32: fractalengine.rpc.v1.GetMintResponse
	(*CreateMintResponse)(nil),              // 33: fractalengine.rpc.v1.CreateMintResponse
	(*ExpandMintResponse)(nil),              // 34: fractalengine.rpc.v1.ExpandMintResponse
	(*CreateNewPaymentResponse)(nil),        // 35: fractalengine.rpc.v1.CreateNewPaymentResponse
	(*GetPendingTokenBalancesResponse)(nil), // 36: fractalengine.rpc.v1.GetPendingTokenBalancesResponse
	(*GetTokenBalancesResponse)(nil),        // 37: fractalengine.rpc.v1.GetTokenBalancesResponse
	(*GetSellOffersResponse)(nil),           // 38: fractalengine.rpc.v1.GetSellOffersResponse
	(*CreateSellOfferResponse)(nil),         // 39: fractalengine.rpc.v1.CreateSellOfferResponse
	(*DeleteSellOfferResponse)(nil),         // 40: fractalengine.rpc.v1.DeleteSellOfferResponse
	(*GetBuyOffersResponse)(nil),            // 41: fractalengine.rpc.v1.GetBuyOffersResponse
	(*CreateBuyOfferResponse)(nil),          // 42: fractalengine.rpc.v1.CreateBuyOfferResponse
	(*DeleteBuyOfferResponse)(nil),          // 43: fractalengine.rpc.v1.DeleteBuyOfferResponse
}
var file_rpc_proto_depIdxs = []int32{
	0,  // 0: fractalengine.rpc.v1.FractalEngineRpcService.DogeConfirm:input_type -> fractalengine.rpc.v1.DogeConfirmRequest
	1,  // 1: fractalengine.rpc.v1.FractalEngineRpcService.DogeSend:input_type -> fractalengine.rpc.v1.DogeSendRequest
	2,  // 2: fractalengine.rpc.v1.FractalEngineRpcService.DogeTopUp:input_type -> fractalengine.rpc.v1.DogeTopUpRequest
	3,  // 3: fractalengine.rpc.v1.FractalEngineRpcService.GetHealth:input_type -> fractalengine.rpc.v1.GetHealthRequest
	4,  // 4: fractalengine.rpc.v1.FractalEngineRpcService.GetStats:input_type -> fractalengine.rpc.v1.GetStatsRequest
	5,  // 5: fractalengine.rpc.v1.FractalEngineRpcService.GetInvoices:input_type -> fractalengine.rpc.v1.GetInvoicesRequest
	6,  // 6: fractalengine.rpc.v1.FractalEngineRpcService.GetAllInvoices:input_type -> fractalengine.rpc.v1.GetAllInvoicesRequest
	7,  // 7: fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoice:input_type -> fractalengine.rpc.v1.CreateInvoiceRequest
	8,  // 8: fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoiceSignature:input_type -> fractalengine.rpc.v1.CreateInvoiceSignatureRequest
	9,  // 9: fractalengine.rpc.v1.FractalEngineRpcService.GetMints:input_type -> fractalengine.rpc.v1.GetMintsRequest
	10, // 10: fractalengine.rpc.v1.FractalEngineRpcService.GetMint:input_type -> fractalengine.rpc.v1.GetMintRequest
	11, // 11: fractalengine.rpc.v1.FractalEngineRpcService.CreateMint:input_type -> fractalengine.rpc.v1.CreateMintRequest
	12, // 12: fractalengine.rpc.v1.FractalEngineRpcService.ExpandMint:input_type -> fractalengine.rpc.v1.ExpandMintRequest
	13, // 13: fractalengine.rpc.v1.FractalEngineRpcService.CreateNewPayment:input_type -> fractalengine.rpc.v1.CreateNewPaymentRequest
	14, // 14: fractalengine.rpc.v1.FractalEngineRpcService.GetPendingTokenBalances:input_type -> fractalengine.rpc.v1.GetPendingTokenBalancesRequest
	15, // 15: fractalengine.rpc.v1.FractalEngineRpcService.GetTokenBalances:input_type -> fractalengine.rpc.v1.GetTokenBalancesRequest
	16, // 16: fractalengine.rpc.v1.FractalEngineRpcService.GetSellOffers:input_type -> fractalengine.rpc.v1.GetSellOffersRequest
	17, // 17: fractalengine.rpc.v1.FractalEngineRpcService.CreateSellOffer:input_type -> fractalengine.rpc.v1.CreateSellOfferRequest
	18, // 18: fractalengine.rpc.v1.FractalEngineRpcService.DeleteSellOffer:input_type -> fractalengine.rpc.v1.DeleteSellOfferRequest
	19, // 19: fractalengine.rpc.v1.FractalEngineRpcService.GetBuyOffers:input_type -> fractalengine.rpc.v1.GetBuyOffersRequest
	20, // 20: fractalengine.rpc.v1.FractalEngineRpcService.CreateBuyOffer:input_type -> fractalengine.rpc.v1.CreateBuyOfferRequest
	21, // 21: fractalengine.rpc.v1.FractalEngineRpcService.DeleteBuyOffer:input_type -> fractalengine.rpc.v1.DeleteBuyOfferRequest
	22, // 22: fractalengine.rpc.v1.FractalEngineRpcService.DogeConfirm:output_type -> fractalengine.rpc.v1.DogeConfirmResponse
	23, // 23: fractalengine.rpc.v1.FractalEngineRpcService.DogeSend:output_type -> fractalengine.rpc.v1.DogeSendResponse
	24, // 24: fractalengine.rpc.v1.FractalEngineRpcService.DogeTopUp:output_type -> fractalengine.rpc.v1.DogeTopUpResponse
	25, // 25: fractalengine.rpc.v1.FractalEngineRpcService.GetHealth:output_type -> fractalengine.rpc.v1.GetHealthResponse
	26, // 26: fractalengine.rpc.v1.FractalEngineRpcService.GetStats:output_type -> fractalengine.rpc.v1.GetStatsResponse
	27, // 27: fractalengine.rpc.v1.FractalEngineRpcService.GetInvoices:output_type -> fractalengine.rpc.v1.GetInvoicesResponse
	28, // 28: fractalengine.rpc.v1.FractalEngineRpcService.GetAllInvoices:output_type -> fractalengine.rpc.v1.GetAllInvoicesResponse
	29, // 29: fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoice:output_type -> fractalengine.rpc.v1.CreateInvoiceResponse
	30, // 30: fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoiceSignature:output_type -> fractalengine.rpc.v1.CreateInvoiceSignatureResponse
	31, // 31: fractalengine.rpc.v1.FractalEngineRpcService.GetMints:output_type -> fractalengine.rpc.v1.GetMintsResponse
	32, // 32: fractalengine.rpc.v1.FractalEngineRpcService.GetMint:output_type -> fractalengine.rpc.v1.GetMintResponse
	33, // 33: fractalengine.rpc.v1.FractalEngineRpcService.CreateMint:output_type -> fractalengine.rpc.v1.CreateMintResponse
	34, // 34: fractalengine.rpc.v1.FractalEngineRpcService.ExpandMint:output_type -> fractalengine.rpc.v1.ExpandMintResponse
	35, // 35: fractalengine.rpc.v1.FractalEngineRpcService.CreateNewPayment:output_type -> fractalengine.rpc.v1.CreateNewPaymentResponse
	36, // 36: fractalengine.rpc.v1.FractalEngineRpcService.GetPendingTokenBalances:output_type -> fractalengine.rpc.v1.GetPendingTokenBalancesResponse
	37, // 37: fractalengine.rpc.v1.FractalEngineRpcService.GetTokenBalances:output_type -> fractalengine.rpc.v1.GetTokenBalancesResponse
	38, // 38: fractalengine.rpc.v1.FractalEngineRpcService.GetSellOffers:output_type -> fractalengine.rpc.v1.GetSellOffersResponse
	39, // 39: fractalengine.rpc.v1.FractalEngineRpcService.CreateSellOffer:output_type -> fractalengine.rpc.v1.CreateSellOfferResponse
	40, // 40: fractalengine.rpc.v1.FractalEngineRpcService.DeleteSellOffer:output_type -> fractalengine.rpc.v1.DeleteSellOfferResponse
	41, // 41: fractalengine.rpc.v1.FractalEngineRpcService.GetBuyOffers:output_type -> fractalengine.rpc.v1.GetBuyOffersResponse
	42, // 42: fractalengine.rpc.v1.FractalEngineRpcService.CreateBuyOffer:output_type -> fractalengine.rpc.v1.CreateBuyOfferResponse
	43, // 43: fractalengine.rpc.v1.FractalEngineRpcService.DeleteBuyOffer:output_type -> fractalengine.rpc.v1.DeleteBuyOfferResponse
	22, // [22:44] is the sub-list for method output_type
	0,  // [0:22] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_doge_proto_init()
	file_health_proto_init()
	file_invoices_proto_init()
	file_mints_proto_init()
	file_offers_proto_init()
	file_payments_proto_init()
	file_stats_proto_init()
	file_tokens_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
