// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tokens.proto

package protocol

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPendingTokenBalancesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Address       string                  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MintHash      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTokenBalancesRequest) Reset() {
	*x = GetPendingTokenBalancesRequest{}
	mi := &file_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTokenBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTokenBalancesRequest) ProtoMessage() {}

func (x *GetPendingTokenBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTokenBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetPendingTokenBalancesRequest) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *GetPendingTokenBalancesRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetPendingTokenBalancesRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.MintHash
	}
	return nil
}

type GetPendingTokenBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*TokenBalance        `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTokenBalancesResponse) Reset() {
	*x = GetPendingTokenBalancesResponse{}
	mi := &file_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTokenBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTokenBalancesResponse) ProtoMessage() {}

func (x *GetPendingTokenBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTokenBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetPendingTokenBalancesResponse) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingTokenBalancesResponse) GetBalances() []*TokenBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type GetTokenBalancesRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Address            string                  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MintHash           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	IncludeMintDetails *wrapperspb.BoolValue   `protobuf:"bytes,3,opt,name=include_mint_details,json=includeMintDetails,proto3" json:"include_mint_details,omitempty"`
	Limit              *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Page               *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTokenBalancesRequest) Reset() {
	*x = GetTokenBalancesRequest{}
	mi := &file_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenBalancesRequest) ProtoMessage() {}

func (x *GetTokenBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetTokenBalancesRequest) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenBalancesRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenBalancesRequest) GetMintHash() *wrapperspb.StringValue {
	if x != nil {
		return x.MintHash
	}
	return nil
}

func (x *GetTokenBalancesRequest) GetIncludeMintDetails() *wrapperspb.BoolValue {
	if x != nil {
		return x.IncludeMintDetails
	}
	return nil
}

func (x *GetTokenBalancesRequest) GetLimit() *wrapperspb.Int32Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *GetTokenBalancesRequest) GetPage() *wrapperspb.Int32Value {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetTokenBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenBalancesResponse) Reset() {
	*x = GetTokenBalancesResponse{}
	mi := &file_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenBalancesResponse) ProtoMessage() {}

func (x *GetTokenBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetTokenBalancesResponse) Descriptor() ([]byte, []int) {
	return file_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenBalancesResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tokens_proto protoreflect.FileDescriptor

const file_tokens_proto_rawDesc = "" +
	"\n" +
	"\ftokens.proto\x12\x14fractalengine.rpc.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\fcommon.proto\"\xc0\x01\n" +
	"\x1eGetPendingTokenBalancesRequest\x12I\n" +
	"\aaddress\x18\x01 \x01(\tB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\aaddress\x12S\n" +
	"\tmint_hash\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\"a\n" +
	"\x1fGetPendingTokenBalancesResponse\x12>\n" +
	"\bbalances\x18\x01 \x03(\v2\".fractalengine.rpc.v1.TokenBalanceR\bbalances\"\xeb\x02\n" +
	"\x17GetTokenBalancesRequest\x12I\n" +
	"\aaddress\x18\x01 \x01(\tB/\xbaH,r*2(^(?:[DAmn2])[1-9A-HJ-NP-Za-km-z]{25,34}$R\aaddress\x12S\n" +
	"\tmint_hash\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\x18\xbaH\x15r\x132\x11^[a-fA-F0-9]{64}$R\bmintHash\x12L\n" +
	"\x14include_mint_details\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\x12includeMintDetails\x121\n" +
	"\x05limit\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05limit\x12/\n" +
	"\x04page\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04page\"G\n" +
	"\x18GetTokenBalancesResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04dataB\x12Z\x10pkg/rpc/protocolb\x06proto3"

var (
	file_tokens_proto_rawDescOnce sync.Once
	file_tokens_proto_rawDescData []byte
)

func file_tokens_proto_rawDescGZIP() []byte {
	file_tokens_proto_rawDescOnce.Do(func() {
		file_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)))
	})
	return file_tokens_proto_rawDescData
}

var file_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tokens_proto_goTypes = []any{
	(*GetPendingTokenBalancesRequest)(nil),  // 0: fractalengine.rpc.v1.GetPendingTokenBalancesRequest
	(*GetPendingTokenBalancesResponse)(nil), // 1: fractalengine.rpc.v1.GetPendingTokenBalancesResponse
	(*GetTokenBalancesRequest)(nil),         // 2: fractalengine.rpc.v1.GetTokenBalancesRequest
	(*GetTokenBalancesResponse)(nil),        // 3: fractalengine.rpc.v1.GetTokenBalancesResponse
	(*wrapperspb.StringValue)(nil),          // 4: google.protobuf.StringValue
	(*TokenBalance)(nil),                    // 5: fractalengine.rpc.v1.TokenBalance
	(*wrapperspb.BoolValue)(nil),            // 6: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),           // 7: google.protobuf.Int32Value
	(*structpb.Struct)(nil),                 // 8: google.protobuf.Struct
}
var file_tokens_proto_depIdxs = []int32{
	4, // 0: fractalengine.rpc.v1.GetPendingTokenBalancesRequest.mint_hash:type_name -> google.protobuf.StringValue
	5, // 1: fractalengine.rpc.v1.GetPendingTokenBalancesResponse.balances:type_name -> fractalengine.rpc.v1.TokenBalance
	4, // 2: fractalengine.rpc.v1.GetTokenBalancesRequest.mint_hash:type_name -> google.protobuf.StringValue
	6, // 3: fractalengine.rpc.v1.GetTokenBalancesRequest.include_mint_details:type_name -> google.protobuf.BoolValue
	7, // 4: fractalengine.rpc.v1.GetTokenBalancesRequest.limit:type_name -> google.protobuf.Int32Value
	7, // 5: fractalengine.rpc.v1.GetTokenBalancesRequest.page:type_name -> google.protobuf.Int32Value
	8, // 6: fractalengine.rpc.v1.GetTokenBalancesResponse.data:type_name -> google.protobuf.Struct
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tokens_proto_init() }
func file_tokens_proto_init() {
	if File_tokens_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokens_proto_rawDesc), len(file_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokens_proto_goTypes,
		DependencyIndexes: file_tokens_proto_depIdxs,
		MessageInfos:      file_tokens_proto_msgTypes,
	}.Build()
	File_tokens_proto = out.File
	file_tokens_proto_goTypes = nil
	file_tokens_proto_depIdxs = nil
}
