// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpc.proto

package protocolconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protocol "pkg/rpc/protocol"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FractalEngineRpcServiceName is the fully-qualified name of the FractalEngineRpcService service.
	FractalEngineRpcServiceName = "fractalengine.rpc.v1.FractalEngineRpcService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FractalEngineRpcServiceDogeConfirmProcedure is the fully-qualified name of the
	// FractalEngineRpcService's DogeConfirm RPC.
	FractalEngineRpcServiceDogeConfirmProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/DogeConfirm"
	// FractalEngineRpcServiceDogeSendProcedure is the fully-qualified name of the
	// FractalEngineRpcService's DogeSend RPC.
	FractalEngineRpcServiceDogeSendProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/DogeSend"
	// FractalEngineRpcServiceDogeTopUpProcedure is the fully-qualified name of the
	// FractalEngineRpcService's DogeTopUp RPC.
	FractalEngineRpcServiceDogeTopUpProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/DogeTopUp"
	// FractalEngineRpcServiceGetHealthProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetHealth RPC.
	FractalEngineRpcServiceGetHealthProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetHealth"
	// FractalEngineRpcServiceGetStatsProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetStats RPC.
	FractalEngineRpcServiceGetStatsProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetStats"
	// FractalEngineRpcServiceGetInvoicesProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetInvoices RPC.
	FractalEngineRpcServiceGetInvoicesProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetInvoices"
	// FractalEngineRpcServiceGetAllInvoicesProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetAllInvoices RPC.
	FractalEngineRpcServiceGetAllInvoicesProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetAllInvoices"
	// FractalEngineRpcServiceCreateInvoiceProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateInvoice RPC.
	FractalEngineRpcServiceCreateInvoiceProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateInvoice"
	// FractalEngineRpcServiceCreateInvoiceSignatureProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateInvoiceSignature RPC.
	FractalEngineRpcServiceCreateInvoiceSignatureProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateInvoiceSignature"
	// FractalEngineRpcServiceGetMintsProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetMints RPC.
	FractalEngineRpcServiceGetMintsProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetMints"
	// FractalEngineRpcServiceGetMintProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetMint RPC.
	FractalEngineRpcServiceGetMintProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetMint"
	// FractalEngineRpcServiceCreateMintProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateMint RPC.
	FractalEngineRpcServiceCreateMintProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateMint"
	// FractalEngineRpcServiceCreateNewPaymentProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateNewPayment RPC.
	FractalEngineRpcServiceCreateNewPaymentProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateNewPayment"
	// FractalEngineRpcServiceGetPendingTokenBalancesProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetPendingTokenBalances RPC.
	FractalEngineRpcServiceGetPendingTokenBalancesProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetPendingTokenBalances"
	// FractalEngineRpcServiceGetTokenBalancesProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetTokenBalances RPC.
	FractalEngineRpcServiceGetTokenBalancesProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetTokenBalances"
	// FractalEngineRpcServiceGetSellOffersProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetSellOffers RPC.
	FractalEngineRpcServiceGetSellOffersProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetSellOffers"
	// FractalEngineRpcServiceCreateSellOfferProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateSellOffer RPC.
	FractalEngineRpcServiceCreateSellOfferProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateSellOffer"
	// FractalEngineRpcServiceDeleteSellOfferProcedure is the fully-qualified name of the
	// FractalEngineRpcService's DeleteSellOffer RPC.
	FractalEngineRpcServiceDeleteSellOfferProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/DeleteSellOffer"
	// FractalEngineRpcServiceGetBuyOffersProcedure is the fully-qualified name of the
	// FractalEngineRpcService's GetBuyOffers RPC.
	FractalEngineRpcServiceGetBuyOffersProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/GetBuyOffers"
	// FractalEngineRpcServiceCreateBuyOfferProcedure is the fully-qualified name of the
	// FractalEngineRpcService's CreateBuyOffer RPC.
	FractalEngineRpcServiceCreateBuyOfferProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/CreateBuyOffer"
	// FractalEngineRpcServiceDeleteBuyOfferProcedure is the fully-qualified name of the
	// FractalEngineRpcService's DeleteBuyOffer RPC.
	FractalEngineRpcServiceDeleteBuyOfferProcedure = "/fractalengine.rpc.v1.FractalEngineRpcService/DeleteBuyOffer"
)

// FractalEngineRpcServiceClient is a client for the fractalengine.rpc.v1.FractalEngineRpcService
// service.
type FractalEngineRpcServiceClient interface {
	DogeConfirm(context.Context, *connect.Request[protocol.DogeConfirmRequest]) (*connect.Response[protocol.DogeConfirmResponse], error)
	DogeSend(context.Context, *connect.Request[protocol.DogeSendRequest]) (*connect.Response[protocol.DogeSendResponse], error)
	DogeTopUp(context.Context, *connect.Request[protocol.DogeTopUpRequest]) (*connect.Response[protocol.DogeTopUpResponse], error)
	GetHealth(context.Context, *connect.Request[protocol.GetHealthRequest]) (*connect.Response[protocol.GetHealthResponse], error)
	GetStats(context.Context, *connect.Request[protocol.GetStatsRequest]) (*connect.Response[protocol.GetStatsResponse], error)
	GetInvoices(context.Context, *connect.Request[protocol.GetInvoicesRequest]) (*connect.Response[protocol.GetInvoicesResponse], error)
	GetAllInvoices(context.Context, *connect.Request[protocol.GetAllInvoicesRequest]) (*connect.Response[protocol.GetAllInvoicesResponse], error)
	CreateInvoice(context.Context, *connect.Request[protocol.CreateInvoiceRequest]) (*connect.Response[protocol.CreateInvoiceResponse], error)
	CreateInvoiceSignature(context.Context, *connect.Request[protocol.CreateInvoiceSignatureRequest]) (*connect.Response[protocol.CreateInvoiceSignatureResponse], error)
	GetMints(context.Context, *connect.Request[protocol.GetMintsRequest]) (*connect.Response[protocol.GetMintsResponse], error)
	GetMint(context.Context, *connect.Request[protocol.GetMintRequest]) (*connect.Response[protocol.GetMintResponse], error)
	CreateMint(context.Context, *connect.Request[protocol.CreateMintRequest]) (*connect.Response[protocol.CreateMintResponse], error)
	CreateNewPayment(context.Context, *connect.Request[protocol.CreateNewPaymentRequest]) (*connect.Response[protocol.CreateNewPaymentResponse], error)
	GetPendingTokenBalances(context.Context, *connect.Request[protocol.GetPendingTokenBalancesRequest]) (*connect.Response[protocol.GetPendingTokenBalancesResponse], error)
	GetTokenBalances(context.Context, *connect.Request[protocol.GetTokenBalancesRequest]) (*connect.Response[protocol.GetTokenBalancesResponse], error)
	GetSellOffers(context.Context, *connect.Request[protocol.GetSellOffersRequest]) (*connect.Response[protocol.GetSellOffersResponse], error)
	CreateSellOffer(context.Context, *connect.Request[protocol.CreateSellOfferRequest]) (*connect.Response[protocol.CreateSellOfferResponse], error)
	DeleteSellOffer(context.Context, *connect.Request[protocol.DeleteSellOfferRequest]) (*connect.Response[protocol.DeleteSellOfferResponse], error)
	GetBuyOffers(context.Context, *connect.Request[protocol.GetBuyOffersRequest]) (*connect.Response[protocol.GetBuyOffersResponse], error)
	CreateBuyOffer(context.Context, *connect.Request[protocol.CreateBuyOfferRequest]) (*connect.Response[protocol.CreateBuyOfferResponse], error)
	DeleteBuyOffer(context.Context, *connect.Request[protocol.DeleteBuyOfferRequest]) (*connect.Response[protocol.DeleteBuyOfferResponse], error)
}

// NewFractalEngineRpcServiceClient constructs a client for the
// fractalengine.rpc.v1.FractalEngineRpcService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFractalEngineRpcServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FractalEngineRpcServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fractalEngineRpcServiceMethods := protocol.File_rpc_proto.Services().ByName("FractalEngineRpcService").Methods()
	return &fractalEngineRpcServiceClient{
		dogeConfirm: connect.NewClient[protocol.DogeConfirmRequest, protocol.DogeConfirmResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceDogeConfirmProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeConfirm")),
			connect.WithClientOptions(opts...),
		),
		dogeSend: connect.NewClient[protocol.DogeSendRequest, protocol.DogeSendResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceDogeSendProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeSend")),
			connect.WithClientOptions(opts...),
		),
		dogeTopUp: connect.NewClient[protocol.DogeTopUpRequest, protocol.DogeTopUpResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceDogeTopUpProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeTopUp")),
			connect.WithClientOptions(opts...),
		),
		getHealth: connect.NewClient[protocol.GetHealthRequest, protocol.GetHealthResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetHealthProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetHealth")),
			connect.WithClientOptions(opts...),
		),
		getStats: connect.NewClient[protocol.GetStatsRequest, protocol.GetStatsResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetStatsProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetStats")),
			connect.WithClientOptions(opts...),
		),
		getInvoices: connect.NewClient[protocol.GetInvoicesRequest, protocol.GetInvoicesResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetInvoicesProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetInvoices")),
			connect.WithClientOptions(opts...),
		),
		getAllInvoices: connect.NewClient[protocol.GetAllInvoicesRequest, protocol.GetAllInvoicesResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetAllInvoicesProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetAllInvoices")),
			connect.WithClientOptions(opts...),
		),
		createInvoice: connect.NewClient[protocol.CreateInvoiceRequest, protocol.CreateInvoiceResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateInvoiceProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateInvoice")),
			connect.WithClientOptions(opts...),
		),
		createInvoiceSignature: connect.NewClient[protocol.CreateInvoiceSignatureRequest, protocol.CreateInvoiceSignatureResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateInvoiceSignatureProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateInvoiceSignature")),
			connect.WithClientOptions(opts...),
		),
		getMints: connect.NewClient[protocol.GetMintsRequest, protocol.GetMintsResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetMintsProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetMints")),
			connect.WithClientOptions(opts...),
		),
		getMint: connect.NewClient[protocol.GetMintRequest, protocol.GetMintResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetMintProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetMint")),
			connect.WithClientOptions(opts...),
		),
		createMint: connect.NewClient[protocol.CreateMintRequest, protocol.CreateMintResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateMintProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateMint")),
			connect.WithClientOptions(opts...),
		),
		createNewPayment: connect.NewClient[protocol.CreateNewPaymentRequest, protocol.CreateNewPaymentResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateNewPaymentProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateNewPayment")),
			connect.WithClientOptions(opts...),
		),
		getPendingTokenBalances: connect.NewClient[protocol.GetPendingTokenBalancesRequest, protocol.GetPendingTokenBalancesResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetPendingTokenBalancesProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetPendingTokenBalances")),
			connect.WithClientOptions(opts...),
		),
		getTokenBalances: connect.NewClient[protocol.GetTokenBalancesRequest, protocol.GetTokenBalancesResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetTokenBalancesProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetTokenBalances")),
			connect.WithClientOptions(opts...),
		),
		getSellOffers: connect.NewClient[protocol.GetSellOffersRequest, protocol.GetSellOffersResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetSellOffersProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetSellOffers")),
			connect.WithClientOptions(opts...),
		),
		createSellOffer: connect.NewClient[protocol.CreateSellOfferRequest, protocol.CreateSellOfferResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateSellOfferProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateSellOffer")),
			connect.WithClientOptions(opts...),
		),
		deleteSellOffer: connect.NewClient[protocol.DeleteSellOfferRequest, protocol.DeleteSellOfferResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceDeleteSellOfferProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DeleteSellOffer")),
			connect.WithClientOptions(opts...),
		),
		getBuyOffers: connect.NewClient[protocol.GetBuyOffersRequest, protocol.GetBuyOffersResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceGetBuyOffersProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetBuyOffers")),
			connect.WithClientOptions(opts...),
		),
		createBuyOffer: connect.NewClient[protocol.CreateBuyOfferRequest, protocol.CreateBuyOfferResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceCreateBuyOfferProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateBuyOffer")),
			connect.WithClientOptions(opts...),
		),
		deleteBuyOffer: connect.NewClient[protocol.DeleteBuyOfferRequest, protocol.DeleteBuyOfferResponse](
			httpClient,
			baseURL+FractalEngineRpcServiceDeleteBuyOfferProcedure,
			connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DeleteBuyOffer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fractalEngineRpcServiceClient implements FractalEngineRpcServiceClient.
type fractalEngineRpcServiceClient struct {
	dogeConfirm             *connect.Client[protocol.DogeConfirmRequest, protocol.DogeConfirmResponse]
	dogeSend                *connect.Client[protocol.DogeSendRequest, protocol.DogeSendResponse]
	dogeTopUp               *connect.Client[protocol.DogeTopUpRequest, protocol.DogeTopUpResponse]
	getHealth               *connect.Client[protocol.GetHealthRequest, protocol.GetHealthResponse]
	getStats                *connect.Client[protocol.GetStatsRequest, protocol.GetStatsResponse]
	getInvoices             *connect.Client[protocol.GetInvoicesRequest, protocol.GetInvoicesResponse]
	getAllInvoices          *connect.Client[protocol.GetAllInvoicesRequest, protocol.GetAllInvoicesResponse]
	createInvoice           *connect.Client[protocol.CreateInvoiceRequest, protocol.CreateInvoiceResponse]
	createInvoiceSignature  *connect.Client[protocol.CreateInvoiceSignatureRequest, protocol.CreateInvoiceSignatureResponse]
	getMints                *connect.Client[protocol.GetMintsRequest, protocol.GetMintsResponse]
	getMint                 *connect.Client[protocol.GetMintRequest, protocol.GetMintResponse]
	createMint              *connect.Client[protocol.CreateMintRequest, protocol.CreateMintResponse]
	createNewPayment        *connect.Client[protocol.CreateNewPaymentRequest, protocol.CreateNewPaymentResponse]
	getPendingTokenBalances *connect.Client[protocol.GetPendingTokenBalancesRequest, protocol.GetPendingTokenBalancesResponse]
	getTokenBalances        *connect.Client[protocol.GetTokenBalancesRequest, protocol.GetTokenBalancesResponse]
	getSellOffers           *connect.Client[protocol.GetSellOffersRequest, protocol.GetSellOffersResponse]
	createSellOffer         *connect.Client[protocol.CreateSellOfferRequest, protocol.CreateSellOfferResponse]
	deleteSellOffer         *connect.Client[protocol.DeleteSellOfferRequest, protocol.DeleteSellOfferResponse]
	getBuyOffers            *connect.Client[protocol.GetBuyOffersRequest, protocol.GetBuyOffersResponse]
	createBuyOffer          *connect.Client[protocol.CreateBuyOfferRequest, protocol.CreateBuyOfferResponse]
	deleteBuyOffer          *connect.Client[protocol.DeleteBuyOfferRequest, protocol.DeleteBuyOfferResponse]
}

// DogeConfirm calls fractalengine.rpc.v1.FractalEngineRpcService.DogeConfirm.
func (c *fractalEngineRpcServiceClient) DogeConfirm(ctx context.Context, req *connect.Request[protocol.DogeConfirmRequest]) (*connect.Response[protocol.DogeConfirmResponse], error) {
	return c.dogeConfirm.CallUnary(ctx, req)
}

// DogeSend calls fractalengine.rpc.v1.FractalEngineRpcService.DogeSend.
func (c *fractalEngineRpcServiceClient) DogeSend(ctx context.Context, req *connect.Request[protocol.DogeSendRequest]) (*connect.Response[protocol.DogeSendResponse], error) {
	return c.dogeSend.CallUnary(ctx, req)
}

// DogeTopUp calls fractalengine.rpc.v1.FractalEngineRpcService.DogeTopUp.
func (c *fractalEngineRpcServiceClient) DogeTopUp(ctx context.Context, req *connect.Request[protocol.DogeTopUpRequest]) (*connect.Response[protocol.DogeTopUpResponse], error) {
	return c.dogeTopUp.CallUnary(ctx, req)
}

// GetHealth calls fractalengine.rpc.v1.FractalEngineRpcService.GetHealth.
func (c *fractalEngineRpcServiceClient) GetHealth(ctx context.Context, req *connect.Request[protocol.GetHealthRequest]) (*connect.Response[protocol.GetHealthResponse], error) {
	return c.getHealth.CallUnary(ctx, req)
}

// GetStats calls fractalengine.rpc.v1.FractalEngineRpcService.GetStats.
func (c *fractalEngineRpcServiceClient) GetStats(ctx context.Context, req *connect.Request[protocol.GetStatsRequest]) (*connect.Response[protocol.GetStatsResponse], error) {
	return c.getStats.CallUnary(ctx, req)
}

// GetInvoices calls fractalengine.rpc.v1.FractalEngineRpcService.GetInvoices.
func (c *fractalEngineRpcServiceClient) GetInvoices(ctx context.Context, req *connect.Request[protocol.GetInvoicesRequest]) (*connect.Response[protocol.GetInvoicesResponse], error) {
	return c.getInvoices.CallUnary(ctx, req)
}

// GetAllInvoices calls fractalengine.rpc.v1.FractalEngineRpcService.GetAllInvoices.
func (c *fractalEngineRpcServiceClient) GetAllInvoices(ctx context.Context, req *connect.Request[protocol.GetAllInvoicesRequest]) (*connect.Response[protocol.GetAllInvoicesResponse], error) {
	return c.getAllInvoices.CallUnary(ctx, req)
}

// CreateInvoice calls fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoice.
func (c *fractalEngineRpcServiceClient) CreateInvoice(ctx context.Context, req *connect.Request[protocol.CreateInvoiceRequest]) (*connect.Response[protocol.CreateInvoiceResponse], error) {
	return c.createInvoice.CallUnary(ctx, req)
}

// CreateInvoiceSignature calls fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoiceSignature.
func (c *fractalEngineRpcServiceClient) CreateInvoiceSignature(ctx context.Context, req *connect.Request[protocol.CreateInvoiceSignatureRequest]) (*connect.Response[protocol.CreateInvoiceSignatureResponse], error) {
	return c.createInvoiceSignature.CallUnary(ctx, req)
}

// GetMints calls fractalengine.rpc.v1.FractalEngineRpcService.GetMints.
func (c *fractalEngineRpcServiceClient) GetMints(ctx context.Context, req *connect.Request[protocol.GetMintsRequest]) (*connect.Response[protocol.GetMintsResponse], error) {
	return c.getMints.CallUnary(ctx, req)
}

// GetMint calls fractalengine.rpc.v1.FractalEngineRpcService.GetMint.
func (c *fractalEngineRpcServiceClient) GetMint(ctx context.Context, req *connect.Request[protocol.GetMintRequest]) (*connect.Response[protocol.GetMintResponse], error) {
	return c.getMint.CallUnary(ctx, req)
}

// CreateMint calls fractalengine.rpc.v1.FractalEngineRpcService.CreateMint.
func (c *fractalEngineRpcServiceClient) CreateMint(ctx context.Context, req *connect.Request[protocol.CreateMintRequest]) (*connect.Response[protocol.CreateMintResponse], error) {
	return c.createMint.CallUnary(ctx, req)
}

// CreateNewPayment calls fractalengine.rpc.v1.FractalEngineRpcService.CreateNewPayment.
func (c *fractalEngineRpcServiceClient) CreateNewPayment(ctx context.Context, req *connect.Request[protocol.CreateNewPaymentRequest]) (*connect.Response[protocol.CreateNewPaymentResponse], error) {
	return c.createNewPayment.CallUnary(ctx, req)
}

// GetPendingTokenBalances calls
// fractalengine.rpc.v1.FractalEngineRpcService.GetPendingTokenBalances.
func (c *fractalEngineRpcServiceClient) GetPendingTokenBalances(ctx context.Context, req *connect.Request[protocol.GetPendingTokenBalancesRequest]) (*connect.Response[protocol.GetPendingTokenBalancesResponse], error) {
	return c.getPendingTokenBalances.CallUnary(ctx, req)
}

// GetTokenBalances calls fractalengine.rpc.v1.FractalEngineRpcService.GetTokenBalances.
func (c *fractalEngineRpcServiceClient) GetTokenBalances(ctx context.Context, req *connect.Request[protocol.GetTokenBalancesRequest]) (*connect.Response[protocol.GetTokenBalancesResponse], error) {
	return c.getTokenBalances.CallUnary(ctx, req)
}

// GetSellOffers calls fractalengine.rpc.v1.FractalEngineRpcService.GetSellOffers.
func (c *fractalEngineRpcServiceClient) GetSellOffers(ctx context.Context, req *connect.Request[protocol.GetSellOffersRequest]) (*connect.Response[protocol.GetSellOffersResponse], error) {
	return c.getSellOffers.CallUnary(ctx, req)
}

// CreateSellOffer calls fractalengine.rpc.v1.FractalEngineRpcService.CreateSellOffer.
func (c *fractalEngineRpcServiceClient) CreateSellOffer(ctx context.Context, req *connect.Request[protocol.CreateSellOfferRequest]) (*connect.Response[protocol.CreateSellOfferResponse], error) {
	return c.createSellOffer.CallUnary(ctx, req)
}

// DeleteSellOffer calls fractalengine.rpc.v1.FractalEngineRpcService.DeleteSellOffer.
func (c *fractalEngineRpcServiceClient) DeleteSellOffer(ctx context.Context, req *connect.Request[protocol.DeleteSellOfferRequest]) (*connect.Response[protocol.DeleteSellOfferResponse], error) {
	return c.deleteSellOffer.CallUnary(ctx, req)
}

// GetBuyOffers calls fractalengine.rpc.v1.FractalEngineRpcService.GetBuyOffers.
func (c *fractalEngineRpcServiceClient) GetBuyOffers(ctx context.Context, req *connect.Request[protocol.GetBuyOffersRequest]) (*connect.Response[protocol.GetBuyOffersResponse], error) {
	return c.getBuyOffers.CallUnary(ctx, req)
}

// CreateBuyOffer calls fractalengine.rpc.v1.FractalEngineRpcService.CreateBuyOffer.
func (c *fractalEngineRpcServiceClient) CreateBuyOffer(ctx context.Context, req *connect.Request[protocol.CreateBuyOfferRequest]) (*connect.Response[protocol.CreateBuyOfferResponse], error) {
	return c.createBuyOffer.CallUnary(ctx, req)
}

// DeleteBuyOffer calls fractalengine.rpc.v1.FractalEngineRpcService.DeleteBuyOffer.
func (c *fractalEngineRpcServiceClient) DeleteBuyOffer(ctx context.Context, req *connect.Request[protocol.DeleteBuyOfferRequest]) (*connect.Response[protocol.DeleteBuyOfferResponse], error) {
	return c.deleteBuyOffer.CallUnary(ctx, req)
}

// FractalEngineRpcServiceHandler is an implementation of the
// fractalengine.rpc.v1.FractalEngineRpcService service.
type FractalEngineRpcServiceHandler interface {
	DogeConfirm(context.Context, *connect.Request[protocol.DogeConfirmRequest]) (*connect.Response[protocol.DogeConfirmResponse], error)
	DogeSend(context.Context, *connect.Request[protocol.DogeSendRequest]) (*connect.Response[protocol.DogeSendResponse], error)
	DogeTopUp(context.Context, *connect.Request[protocol.DogeTopUpRequest]) (*connect.Response[protocol.DogeTopUpResponse], error)
	GetHealth(context.Context, *connect.Request[protocol.GetHealthRequest]) (*connect.Response[protocol.GetHealthResponse], error)
	GetStats(context.Context, *connect.Request[protocol.GetStatsRequest]) (*connect.Response[protocol.GetStatsResponse], error)
	GetInvoices(context.Context, *connect.Request[protocol.GetInvoicesRequest]) (*connect.Response[protocol.GetInvoicesResponse], error)
	GetAllInvoices(context.Context, *connect.Request[protocol.GetAllInvoicesRequest]) (*connect.Response[protocol.GetAllInvoicesResponse], error)
	CreateInvoice(context.Context, *connect.Request[protocol.CreateInvoiceRequest]) (*connect.Response[protocol.CreateInvoiceResponse], error)
	CreateInvoiceSignature(context.Context, *connect.Request[protocol.CreateInvoiceSignatureRequest]) (*connect.Response[protocol.CreateInvoiceSignatureResponse], error)
	GetMints(context.Context, *connect.Request[protocol.GetMintsRequest]) (*connect.Response[protocol.GetMintsResponse], error)
	GetMint(context.Context, *connect.Request[protocol.GetMintRequest]) (*connect.Response[protocol.GetMintResponse], error)
	CreateMint(context.Context, *connect.Request[protocol.CreateMintRequest]) (*connect.Response[protocol.CreateMintResponse], error)
	CreateNewPayment(context.Context, *connect.Request[protocol.CreateNewPaymentRequest]) (*connect.Response[protocol.CreateNewPaymentResponse], error)
	GetPendingTokenBalances(context.Context, *connect.Request[protocol.GetPendingTokenBalancesRequest]) (*connect.Response[protocol.GetPendingTokenBalancesResponse], error)
	GetTokenBalances(context.Context, *connect.Request[protocol.GetTokenBalancesRequest]) (*connect.Response[protocol.GetTokenBalancesResponse], error)
	GetSellOffers(context.Context, *connect.Request[protocol.GetSellOffersRequest]) (*connect.Response[protocol.GetSellOffersResponse], error)
	CreateSellOffer(context.Context, *connect.Request[protocol.CreateSellOfferRequest]) (*connect.Response[protocol.CreateSellOfferResponse], error)
	DeleteSellOffer(context.Context, *connect.Request[protocol.DeleteSellOfferRequest]) (*connect.Response[protocol.DeleteSellOfferResponse], error)
	GetBuyOffers(context.Context, *connect.Request[protocol.GetBuyOffersRequest]) (*connect.Response[protocol.GetBuyOffersResponse], error)
	CreateBuyOffer(context.Context, *connect.Request[protocol.CreateBuyOfferRequest]) (*connect.Response[protocol.CreateBuyOfferResponse], error)
	DeleteBuyOffer(context.Context, *connect.Request[protocol.DeleteBuyOfferRequest]) (*connect.Response[protocol.DeleteBuyOfferResponse], error)
}

// NewFractalEngineRpcServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFractalEngineRpcServiceHandler(svc FractalEngineRpcServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fractalEngineRpcServiceMethods := protocol.File_rpc_proto.Services().ByName("FractalEngineRpcService").Methods()
	fractalEngineRpcServiceDogeConfirmHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceDogeConfirmProcedure,
		svc.DogeConfirm,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeConfirm")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceDogeSendHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceDogeSendProcedure,
		svc.DogeSend,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeSend")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceDogeTopUpHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceDogeTopUpProcedure,
		svc.DogeTopUp,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DogeTopUp")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetHealthHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetHealthProcedure,
		svc.GetHealth,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetHealth")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetStatsHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetStatsProcedure,
		svc.GetStats,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetStats")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetInvoicesHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetInvoicesProcedure,
		svc.GetInvoices,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetInvoices")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetAllInvoicesHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetAllInvoicesProcedure,
		svc.GetAllInvoices,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetAllInvoices")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateInvoiceHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateInvoiceProcedure,
		svc.CreateInvoice,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateInvoice")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateInvoiceSignatureHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateInvoiceSignatureProcedure,
		svc.CreateInvoiceSignature,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateInvoiceSignature")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetMintsHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetMintsProcedure,
		svc.GetMints,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetMints")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetMintHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetMintProcedure,
		svc.GetMint,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetMint")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateMintHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateMintProcedure,
		svc.CreateMint,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateMint")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateNewPaymentHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateNewPaymentProcedure,
		svc.CreateNewPayment,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateNewPayment")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetPendingTokenBalancesHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetPendingTokenBalancesProcedure,
		svc.GetPendingTokenBalances,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetPendingTokenBalances")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetTokenBalancesHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetTokenBalancesProcedure,
		svc.GetTokenBalances,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetTokenBalances")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetSellOffersHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetSellOffersProcedure,
		svc.GetSellOffers,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetSellOffers")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateSellOfferHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateSellOfferProcedure,
		svc.CreateSellOffer,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateSellOffer")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceDeleteSellOfferHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceDeleteSellOfferProcedure,
		svc.DeleteSellOffer,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DeleteSellOffer")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceGetBuyOffersHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceGetBuyOffersProcedure,
		svc.GetBuyOffers,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("GetBuyOffers")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceCreateBuyOfferHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceCreateBuyOfferProcedure,
		svc.CreateBuyOffer,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("CreateBuyOffer")),
		connect.WithHandlerOptions(opts...),
	)
	fractalEngineRpcServiceDeleteBuyOfferHandler := connect.NewUnaryHandler(
		FractalEngineRpcServiceDeleteBuyOfferProcedure,
		svc.DeleteBuyOffer,
		connect.WithSchema(fractalEngineRpcServiceMethods.ByName("DeleteBuyOffer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fractalengine.rpc.v1.FractalEngineRpcService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FractalEngineRpcServiceDogeConfirmProcedure:
			fractalEngineRpcServiceDogeConfirmHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceDogeSendProcedure:
			fractalEngineRpcServiceDogeSendHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceDogeTopUpProcedure:
			fractalEngineRpcServiceDogeTopUpHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetHealthProcedure:
			fractalEngineRpcServiceGetHealthHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetStatsProcedure:
			fractalEngineRpcServiceGetStatsHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetInvoicesProcedure:
			fractalEngineRpcServiceGetInvoicesHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetAllInvoicesProcedure:
			fractalEngineRpcServiceGetAllInvoicesHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateInvoiceProcedure:
			fractalEngineRpcServiceCreateInvoiceHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateInvoiceSignatureProcedure:
			fractalEngineRpcServiceCreateInvoiceSignatureHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetMintsProcedure:
			fractalEngineRpcServiceGetMintsHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetMintProcedure:
			fractalEngineRpcServiceGetMintHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateMintProcedure:
			fractalEngineRpcServiceCreateMintHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateNewPaymentProcedure:
			fractalEngineRpcServiceCreateNewPaymentHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetPendingTokenBalancesProcedure:
			fractalEngineRpcServiceGetPendingTokenBalancesHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetTokenBalancesProcedure:
			fractalEngineRpcServiceGetTokenBalancesHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetSellOffersProcedure:
			fractalEngineRpcServiceGetSellOffersHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateSellOfferProcedure:
			fractalEngineRpcServiceCreateSellOfferHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceDeleteSellOfferProcedure:
			fractalEngineRpcServiceDeleteSellOfferHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceGetBuyOffersProcedure:
			fractalEngineRpcServiceGetBuyOffersHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceCreateBuyOfferProcedure:
			fractalEngineRpcServiceCreateBuyOfferHandler.ServeHTTP(w, r)
		case FractalEngineRpcServiceDeleteBuyOfferProcedure:
			fractalEngineRpcServiceDeleteBuyOfferHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFractalEngineRpcServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFractalEngineRpcServiceHandler struct{}

func (UnimplementedFractalEngineRpcServiceHandler) DogeConfirm(context.Context, *connect.Request[protocol.DogeConfirmRequest]) (*connect.Response[protocol.DogeConfirmResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.DogeConfirm is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) DogeSend(context.Context, *connect.Request[protocol.DogeSendRequest]) (*connect.Response[protocol.DogeSendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.DogeSend is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) DogeTopUp(context.Context, *connect.Request[protocol.DogeTopUpRequest]) (*connect.Response[protocol.DogeTopUpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.DogeTopUp is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetHealth(context.Context, *connect.Request[protocol.GetHealthRequest]) (*connect.Response[protocol.GetHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetHealth is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetStats(context.Context, *connect.Request[protocol.GetStatsRequest]) (*connect.Response[protocol.GetStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetStats is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetInvoices(context.Context, *connect.Request[protocol.GetInvoicesRequest]) (*connect.Response[protocol.GetInvoicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetInvoices is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetAllInvoices(context.Context, *connect.Request[protocol.GetAllInvoicesRequest]) (*connect.Response[protocol.GetAllInvoicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetAllInvoices is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateInvoice(context.Context, *connect.Request[protocol.CreateInvoiceRequest]) (*connect.Response[protocol.CreateInvoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoice is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateInvoiceSignature(context.Context, *connect.Request[protocol.CreateInvoiceSignatureRequest]) (*connect.Response[protocol.CreateInvoiceSignatureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateInvoiceSignature is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetMints(context.Context, *connect.Request[protocol.GetMintsRequest]) (*connect.Response[protocol.GetMintsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetMints is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetMint(context.Context, *connect.Request[protocol.GetMintRequest]) (*connect.Response[protocol.GetMintResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetMint is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateMint(context.Context, *connect.Request[protocol.CreateMintRequest]) (*connect.Response[protocol.CreateMintResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateMint is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateNewPayment(context.Context, *connect.Request[protocol.CreateNewPaymentRequest]) (*connect.Response[protocol.CreateNewPaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateNewPayment is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetPendingTokenBalances(context.Context, *connect.Request[protocol.GetPendingTokenBalancesRequest]) (*connect.Response[protocol.GetPendingTokenBalancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetPendingTokenBalances is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetTokenBalances(context.Context, *connect.Request[protocol.GetTokenBalancesRequest]) (*connect.Response[protocol.GetTokenBalancesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetTokenBalances is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetSellOffers(context.Context, *connect.Request[protocol.GetSellOffersRequest]) (*connect.Response[protocol.GetSellOffersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetSellOffers is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateSellOffer(context.Context, *connect.Request[protocol.CreateSellOfferRequest]) (*connect.Response[protocol.CreateSellOfferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateSellOffer is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) DeleteSellOffer(context.Context, *connect.Request[protocol.DeleteSellOfferRequest]) (*connect.Response[protocol.DeleteSellOfferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.DeleteSellOffer is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) GetBuyOffers(context.Context, *connect.Request[protocol.GetBuyOffersRequest]) (*connect.Response[protocol.GetBuyOffersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.GetBuyOffers is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) CreateBuyOffer(context.Context, *connect.Request[protocol.CreateBuyOfferRequest]) (*connect.Response[protocol.CreateBuyOfferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.CreateBuyOffer is not implemented"))
}

func (UnimplementedFractalEngineRpcServiceHandler) DeleteBuyOffer(context.Context, *connect.Request[protocol.DeleteBuyOfferRequest]) (*connect.Response[protocol.DeleteBuyOfferResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fractalengine.rpc.v1.FractalEngineRpcService.DeleteBuyOffer is not implemented"))
}
