// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/protocol/mint_expansion.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is what gets written to the OP_RETURN on the L1
type OnChainMintExpansionMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MintHash         []byte                 `protobuf:"bytes,1,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	AdditionalSupply int32                  `protobuf:"varint,2,opt,name=additional_supply,json=additionalSupply,proto3" json:"additional_supply,omitempty"`
	ExpansionHash    []byte                 `protobuf:"bytes,3,opt,name=expansion_hash,json=expansionHash,proto3" json:"expansion_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnChainMintExpansionMessage) Reset() {
	*x = OnChainMintExpansionMessage{}
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainMintExpansionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainMintExpansionMessage) ProtoMessage() {}

func (x *OnChainMintExpansionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainMintExpansionMessage.ProtoReflect.Descriptor instead.
func (*OnChainMintExpansionMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_expansion_proto_rawDescGZIP(), []int{0}
}

func (x *OnChainMintExpansionMessage) GetMintHash() []byte {
	if x != nil {
		return x.MintHash
	}
	return nil
}

func (x *OnChainMintExpansionMessage) GetAdditionalSupply() int32 {
	if x != nil {
		return x.AdditionalSupply
	}
	return 0
}

func (x *OnChainMintExpansionMessage) GetExpansionHash() []byte {
	if x != nil {
		return x.ExpansionHash
	}
	return nil
}

type MintExpansionMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hash             string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	MintHash         string                 `protobuf:"bytes,2,opt,name=mint_hash,json=mintHash,proto3" json:"mint_hash,omitempty"`
	AdditionalSupply int32                  `protobuf:"varint,3,opt,name=additional_supply,json=additionalSupply,proto3" json:"additional_supply,omitempty"`
	OwnerAddress     string                 `protobuf:"bytes,4,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MintExpansionMessage) Reset() {
	*x = MintExpansionMessage{}
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintExpansionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintExpansionMessage) ProtoMessage() {}

func (x *MintExpansionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintExpansionMessage.ProtoReflect.Descriptor instead.
func (*MintExpansionMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_expansion_proto_rawDescGZIP(), []int{1}
}

func (x *MintExpansionMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MintExpansionMessage) GetMintHash() string {
	if x != nil {
		return x.MintHash
	}
	return ""
}

func (x *MintExpansionMessage) GetAdditionalSupply() int32 {
	if x != nil {
		return x.AdditionalSupply
	}
	return 0
}

func (x *MintExpansionMessage) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *MintExpansionMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MintExpansionMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Payload       *MintExpansionMessage  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintExpansionMessageEnvelope) Reset() {
	*x = MintExpansionMessageEnvelope{}
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintExpansionMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintExpansionMessageEnvelope) ProtoMessage() {}

func (x *MintExpansionMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_mint_expansion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintExpansionMessageEnvelope.ProtoReflect.Descriptor instead.
func (*MintExpansionMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_mint_expansion_proto_rawDescGZIP(), []int{2}
}

func (x *MintExpansionMessageEnvelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MintExpansionMessageEnvelope) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MintExpansionMessageEnvelope) GetPayload() *MintExpansionMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MintExpansionMessageEnvelope) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *MintExpansionMessageEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_pkg_protocol_mint_expansion_proto protoreflect.FileDescriptor

const file_pkg_protocol_mint_expansion_proto_rawDesc = "" +
	"\n" +
	"!pkg/protocol/mint_expansion.proto\x12\rfractalengine\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x1bOnChainMintExpansionMessage\x12\x1b\n" +
	"\tmint_hash\x18\x01 \x01(\fR\bmintHash\x12+\n" +
	"\x11additional_supply\x18\x02 \x01(\x05R\x10additionalSupply\x12%\n" +
	"\x0eexpansion_hash\x18\x03 \x01(\fR\rexpansionHash\"\xd4\x01\n" +
	"\x14MintExpansionMessage\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\tmint_hash\x18\x02 \x01(\tR\bmintHash\x12+\n" +
	"\x11additional_supply\x18\x03 \x01(\x05R\x10additionalSupply\x12#\n" +
	"\rowner_address\x18\x04 \x01(\tR\fownerAddress\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc8\x01\n" +
	"\x1cMintExpansionMessageEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12=\n" +
	"\apayload\x18\x03 \x01(\v2#.fractalengine.MintExpansionMessageR\apayload\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignatureB\x0eZ\fpkg/protocolb\x06proto3"

var (
	file_pkg_protocol_mint_expansion_proto_rawDescOnce sync.Once
	file_pkg_protocol_mint_expansion_proto_rawDescData []byte
)

func file_pkg_protocol_mint_expansion_proto_rawDescGZIP() []byte {
	file_pkg_protocol_mint_expansion_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_mint_expansion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_expansion_proto_rawDesc), len(file_pkg_protocol_mint_expansion_proto_rawDesc)))
	})
	return file_pkg_protocol_mint_expansion_proto_rawDescData
}

var file_pkg_protocol_mint_expansion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_protocol_mint_expansion_proto_goTypes = []any{
	(*OnChainMintExpansionMessage)(nil),  // 0: fractalengine.OnChainMintExpansionMessage
	(*MintExpansionMessage)(nil),         // 1: fractalengine.MintExpansionMessage
	(*MintExpansionMessageEnvelope)(nil), // 2: fractalengine.MintExpansionMessageEnvelope
	(*timestamppb.Timestamp)(nil),        // 3: google.protobuf.Timestamp
}
var file_pkg_protocol_mint_expansion_proto_depIdxs = []int32{
	3, // 0: fractalengine.MintExpansionMessage.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: fractalengine.MintExpansionMessageEnvelope.payload:type_name -> fractalengine.MintExpansionMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_protocol_mint_expansion_proto_init() }
func file_pkg_protocol_mint_expansion_proto_init() {
	if File_pkg_protocol_mint_expansion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_mint_expansion_proto_rawDesc), len(file_pkg_protocol_mint_expansion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_mint_expansion_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_mint_expansion_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_mint_expansion_proto_msgTypes,
	}.Build()
	File_pkg_protocol_mint_expansion_proto = out.File
	file_pkg_protocol_mint_expansion_proto_goTypes = nil
	file_pkg_protocol_mint_expansion_proto_depIdxs = nil
}
